### ISSUE TITLE
Encoder downloads as www-data  how to change to root as videos not showing on website

### ISSUE THREAD

**Issue by k7n2g** [WWBN/AVideo-Encoder#199]
Nothing really in Avideo.log believe if I change upload videos to root not www-data should work can you tell me how to change to root, Have changed encoder file to root but still get www-data when uploading video

**Comment by DanielnetoDotCom** [comment]
I do not think you can do that, www-data is the apache user

also, I am not sure why you need this

**Comment by k7n2g** [comment]
Hi my Encoder uploads  videos but they are now not showing in user my video but upload in Encoder which is root, they the upload is as www-data  then disappear when uploaded all worked fine before the upgrade to v3 am at a loss to know what to do now

**Comment by DanielnetoDotCom** [comment]
Did you also update your streamer?

Encoder v3.0 requires streamer 8.0

**Comment by k7n2g** [comment]
Sorry it says up to date but is 7.8 will upgrade again thanks Guys.
