### ISSUE TITLE
Fresh install not showing version 3.0 says version 2.3

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo-Encoder#210]
Am I missing something? I downloaded it from here and it is not the newest one. 

Git Pull is telling me it is up to date. 

I do not see the chunk uploader or anything on this fresh encoder install.

**Comment by DanielnetoDotCom** [comment]
Hi

I guess you skipped some step.

I just double check and it is version 3.0 with a chunk uploader

**Comment by JoshWho** [comment]
What step? I downloaded it unzipped it and then uploaded it and ran the installer.

**Comment by DanielnetoDotCom** [comment]
You probable download an old version, make sure you use the `git pull` command to download the latest master branch.

**Comment by JoshWho** [comment]
when I run it is shows this  

Already up to date.

**Comment by DanielnetoDotCom** [comment]
Sorry, I mean `git clone`, not `git pull`

**Comment by JoshWho** [comment]
what is the full command. git clone says I need to know the repository

**Comment by JoshWho** [comment]
Ok I just ran git clone https://github.com/WWBN/AVideo-Encoder.git   and nothing changed

**Comment by JoshWho** [comment]
Ok  I manually downloaded the clone and extracted it in the correct folder and now ran the sql update.

**Comment by DanielnetoDotCom** [comment]
The correct procedure is not download the zip and extract, is just use the` git clone https://github.com/WWBN/AVideo-Encoder.git` command inside your apache web directory, usually /var/www/html

and you will have the latest encoder into it.
