### ISSUE TITLE
This streamer site is not allowed error after domain change

### ISSUE THREAD

**Issue by karthikindia** [WWBN/AVideo-Encoder#213]
Hi Daniel
I tried the tutorial video as per the link you provided me earlier
https://tutorials.avideo.com/video/18/fix-youphptube-url-after-move-server-location-and-ip?channelName=yeshua

I am able to use all the functionalities except the encoder throws an error as in the link image attached
http://pix.cobrasoftwares.org/images/2020/02/22/cuetube_encoder_error.png

Kindly advice

**Comment by akhilleusuggo** [comment]
@karthikindia I'm not sure what exactly is the problem . But you need to add the allowed site into the db ( aparently manually ) , or re install the scritp .

To change it manually recommended to use phpmyadmin 
$ `sudo apt-get install phpmyadmin`
Once done , go to your domain name / IP : www.example.com/phpmyadmin

Username and password of your db
Go to the encoder db ( by default named aVideo-Encoder )
`aVideo-Encoder  > configurations ` , you can see allowedStreamersURL
![image](https://user-images.githubusercontent.com/52116577/75094489-3d49f800-5594-11ea-8577-f2c908de8c98.png)

Replace the old one by the new once . Now try again .
If in the future you want to add more websites , you can do it thou the encoder ( login with the admin encoder user )

![image](https://user-images.githubusercontent.com/52116577/75094543-ba756d00-5594-11ea-966e-7b5b6246b8fe.png)

then hit save .

**Comment by karthikindia** [comment]
that worked thanks
