### ISSUE TITLE
logourl error

### ISSUE THREAD

**Issue by karthikindia** [WWBN/AVideo-Encoder#214]
hi daniel
i am unable to change the domain url for the logo
by default it showing different old domain url after an url change
kindly advice
http://pix.cobrasoftwares.org/images/2020/02/22/youphptube_logo_url.png

**Comment by akhilleusuggo** [comment]
@karthikindia You need to go `Plugins  > CustomizeAdvanced  > logoMenuBarURL` on your web panel 
![image](https://user-images.githubusercontent.com/52116577/75094406-6453fa00-5593-11ea-9fbc-9eeccbfcbce1.png)

Done 
Remember to **clear the cache**

**Comment by karthikindia** [comment]
really helped thanks
