### ISSUE TITLE
encode to streamer

### ISSUE THREAD

**Issue by phonocar** [WWBN/AVideo-Encoder#224]
Hello
No sending from encoder to streamer
it worked and overnight nothing left

PS:google translate

**Comment by DanielnetoDotCom** [comment]
To be able to help you you need to provide a lot more details.

including logs.

**Comment by phonocar** [comment]
hello
the youphptube.log file? in the "video" directory?
comme jai dit plus haut tout marché et du jour au lendemain ca marché plus.
javais deux site streamer vers un site d'encodage et ca marché tres bien et plus rien

**Comment by akhilleusuggo** [comment]
@phonocar post here the encoder logs after a failed encoding

**Comment by joshuanoyce** [comment]
I tried it as well. not working. here are the log files
[youphptube.log](https://github.com/WWBN/AVideo-Encoder/files/4416903/youphptube.log)

**Comment by akhilleusuggo** [comment]
@joshuanoyce are you up to date ?
Because this looks like a very old version

**Comment by phonocar** [comment]
Hello
thanks but it came from "post_max_size" from my streamer
