### ISSUE TITLE
videos stuck on /tmp

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#227]
Some videos get stuck on /tmp
The process of unzipping from /tmp into /video doesn't happen 
Not all , only some of them . At the end of the week , over 102Gb were stuck on /tmp and encoders get stuck all the time on transferring ( endless )

Anyway to debug this error ? Because nothing on logs , neither the apache log on /var/logs/apache2

**Comment by DanielnetoDotCom** [comment]
humm, not sure how this happens.

I have to investigate.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Usually after the hls encoder finishes , all the files are sent to apache tmp files ( /tmp/sysapache

Then start the execution of unzip /tmp/ID /videos/ID
Some videos got stuck there . ( maybe the size of the videos maters there ? )

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you tell me what exactly does the script do after transferring the files to the streamer site ?
The source code can you provide please ?
I've been able to 
`/tmp/ unzip YTPChunk_9msnKA -d /var/www/html/YouPHPTube/videos/_YPTid` ; btw there's a typo on YTP , should be YPT )

But when I did that , the video played well , but the thumbnail mouse hover , does not work properly .
![image](https://user-images.githubusercontent.com/52116577/78875868-38170e80-7a57-11ea-9cf6-5aedfa9b7299.png)

**Comment by DanielnetoDotCom** [comment]
Question: does this happen only with  HLS?

about the missing thumbnails, you may find the answer in the log files.

about the source code, please email me at developer@youphptube.com

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Like I've answered you on the email . I wasn't able to find on the script what happens after the extraction of zipped file .
Some other script runs , but I can't see it on the logs .
Once on the /tmp , runs the unzip FILE -d /path/to/AVideos/videos/YPT_id , but then should be tagged or something .

I'll keep trying to reproduce it .
