### ISSUE TITLE
Video sits in encoder queue but no progress

### ISSUE THREAD

**Issue by ConnerK442** [WWBN/AVideo-Encoder#230]
I am having a problem where I upload a video to my encoder, and this seems to be successful. But the video appears in the queue and then just sits, no progress is made and the video never is viewable in my AVideo site. 

This was previously working, as I have successfully uploaded a video to my site in this same way. So I think I may have broken something, but I am not sure what. I have not been tinkering with the Encoder stuff, at least not intentionally.

Any ideas of what I might try to fix this?

**Comment by DanielnetoDotCom** [comment]
check log files.

**Comment by ConnerK442** [comment]
> check log files.

Where would I find those? Thanks...

**Comment by DanielnetoDotCom** [comment]
here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by ConnerK442** [comment]
> here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

Thank you! I see the below error, do you have any suggestions for this?

[08-Apr-2020 21:03:45 UTC] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/YouPHPTube-Encoder/objects/include_config.php:9
Stack trace:
#0 /var/www/html/YouPHPTube-Encoder/videos/configuration.php(20): require_once()
#1 /var/www/html/YouPHPTube-Encoder/view/run.php(3): require_once('/var/www/html/Y...')
#2 {main}
  thrown in /var/www/html/YouPHPTube-Encoder/objects/include_config.php on line 9

**Comment by akhilleusuggo** [comment]
some mysql modules are missing 
`PHP Fatal error: Uncaught Error: Class 'mysqli' not found in`

You need to fix that first

**Comment by ConnerK442** [comment]
I reinstalled that, and got another error about curl, and reinstalled that as well. Now I am getting an issue where the video begins to upload in the encoder, but progress bar (on upload) never completes and video never goes into the queue...

These are last few lines in log file, I do not see any actual errors for this, it just appears to freeze.

If anyone has any ideas on this, I would really appreciate them. Thank you

[09-Apr-2020 14:08:20 UTC] Verification Start http://35.193.160.198/YouPHPTube/
[09-Apr-2020 14:08:20 UTC] Verification Creating the Cache http://35.193.160.198/YouPHPTube/
[09-Apr-2020 14:08:20 UTC] Verification Response (https://search.avideo.com/verify.php?url=http%3A%2F%2F35.193.160.198%2FYouPHPTube%2F): {"msg":["Start","http:\/\/35.193.160.198\/YouPHPTube\/ Site verified"],"verified":true,"status":"a"}

**Comment by akhilleusuggo** [comment]
how much have you put on php.ini
```
upload_max_filesize
post_max_size
memory_limit
``` 
 ??

**Comment by ConnerK442** [comment]
I did have to change these numbers, they were back to their original values (I set them much higher than original values during set up as required):

upload_max_filesize = 1000M (according to my local, video is ~750M)
post_max_filesize = 1000M
memory_limit = 2000M

After changing values and restarting apache, I am still getting same result. Upload seems to randomly stop and no further progress is made. Upon refreshing encoder page, it will say how much was uploaded but still will not send partial uploaded video to queue. 5 attempts or so and progress has ranged from 30M to 500M+.

Thanks for your help

**Comment by akhilleusuggo** [comment]
Just to make sure things are ok , try to upload a small video , example 50mb

**Comment by ConnerK442** [comment]
Somehow this worked. Encoder appeared to be making no progress, but checked back later in spare time in my actual work, and boom the upload had finished, video was in the queue, and eventually completed encoding and is now live on my site.

I wish I knew what caused this, I will have to investigate. But it seems likely that the issue was NOT with the AVideo/Encoder code. Thank you for your help troubleshooting this!
