### ISSUE TITLE
Disable Bulk Encoder & Advanced Option

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo-Encoder#232]
Hi, 

How can I disable Bulk Encoder & Advanced Option in the Encoder below picture?

![1586586354597](https://user-images.githubusercontent.com/57282919/79037088-5a945d80-7bf8-11ea-9c76-06f336d4bcd6.jpg)

Thanks & BR,

**Comment by DanielnetoDotCom** [comment]
In your `videos/configuration.php` file set the `$global['disableBulkEncode'] = true;`

you cannot remove the advanced options
