### ISSUE TITLE
Mp4s don't show up on MyVideos on streamer

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo-Encoder#235]
Hello, 

when I use encoder, everything goes fine. On the Avideo.log file I can see all the different MP4s have been successfully done. On the streamer site they don't appear as you can see in the picture enclosed.

![image](https://user-images.githubusercontent.com/63721378/79335520-1071eb80-7f1a-11ea-905c-7d08303c763a.png)

**Comment by DanielnetoDotCom** [comment]
Is this video playing?

Do the MP4 files actually exist in the videos directory?

**Comment by tonuzo** [comment]
Yes they do. 
![image](https://user-images.githubusercontent.com/63721378/79336677-0fda5480-7f1c-11ea-9455-05d865fed723.png)

**Comment by DanielnetoDotCom** [comment]
Ok, 

So you have only one video in your lib?
are you sure that is the file name?
is your video playing?

it is probably a cache problem.
try to clear your cache directory.

**Comment by akhilleusuggo** [comment]
Hello , you need at the least 3-4 videos to start displaying videos on the welcome page . 
Just to prove this , upload 2-3 more videos .
Leave a feedback , thanks

**Comment by tonuzo** [comment]
![image](https://user-images.githubusercontent.com/63721378/79337989-6a74b000-7f1e-11ea-90d6-38d3c32d2b8b.png)

I cleared the cache from Streamer, uploaded new video, but result is the same. The video thumbnails are showing on the welcome page, but the videos don't play. And mp4s don't show up on MyVideos page (as you can see in the first post).

**Comment by DanielnetoDotCom** [comment]
That is what I mean. If it does not play, I guess you do not have the video files.

probably you could not process your file correctly.

what version are you running?
try to submit another video and check your logs (encoder and streamer).

**Comment by tonuzo** [comment]
![image](https://user-images.githubusercontent.com/63721378/79338898-f1765800-7f1f-11ea-860e-6ce3500220ca.png)
I noticed that Avideo.log shows "... is Dummy file (0)" There must be a clue :)

**Comment by tonuzo** [comment]
"You are running AVideo Encoder version 3.1!"

**Comment by DanielnetoDotCom** [comment]
yes, it is a clue, that your file was not processed. please check a complete log when you submit a file.

**Comment by tonuzo** [comment]
Everything in log-files were okay to my eyes. I also tested encoding with ffmpeg outside encoder and it worked fine. I don't know what else to do... encoded mp4 files are always empty in streamer's videos libarary.

**Comment by DanielnetoDotCom** [comment]
without seeing the log file I cannot help you.

also, make sure you provide the encoder log file and the streamer log file.

**Comment by tonuzo** [comment]
I sent them to you via email. Thank you Daniel.

**Comment by tonuzo** [comment]
[streamer_avideo.log](https://github.com/WWBN/AVideo-Encoder/files/4483274/streamer_avideo.log)
[encoder_avideo.log](https://github.com/WWBN/AVideo-Encoder/files/4483275/encoder_avideo.log)

**Comment by DanielnetoDotCom** [comment]
In your streamer log, I can see this.

PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding()

Google for that and try to fix.

**Comment by tonuzo** [comment]
Thank you. I fixed this and the error line doesn't appear anymore. But the problem still exist, so I am back in square one. Instance is running on google cloud ubuntu 18.04.

**Comment by DanielnetoDotCom** [comment]
delete both log files, encoder, and streamer.

submit a new video.

share both logs.

**Comment by akhilleusuggo** [comment]
@tonuzo I bet that you're using console google cloud

**Comment by tonuzo** [comment]
[encode_avideo.log](https://github.com/WWBN/AVideo-Encoder/files/4487201/encode_avideo.log)
[streamer_avideo.log](https://github.com/WWBN/AVideo-Encoder/files/4487203/streamer_avideo.log)

**Comment by tonuzo** [comment]
> @tonuzo I bet that you're using console google cloud

Yes

**Comment by DanielnetoDotCom** [comment]
@tonuzo I cannot see any problem.

are you using S3 or B2 or FTP storage?

are some of those plugins enabled?


if you type this `ls -lah /var/www/YouPHPTube/videos/_YPTuniqid_5e98540c59df10.36059448*`

what is the output?

**Comment by tonuzo** [comment]
![image](https://user-images.githubusercontent.com/63721378/79461621-168dc800-7fff-11ea-8f24-ef32080d4bd2.png)
It's running on Google Cloud Platform VM instance on ssd. I don't know anything else about storage type.

**Comment by DanielnetoDotCom** [comment]
ok, definitely the error is the 0 bytes

how big those files suppose to be?

**Comment by tonuzo** [comment]
Maybe I should try to reinstall...

**Comment by DanielnetoDotCom** [comment]
That is one shot, right now I have no clue what is wrong.

**Comment by tonuzo** [comment]
Thank you for your help and time. I'll let you know what happens..

**Comment by akhilleusuggo** [comment]
I've said I bet you're using google cloud , because gives many errors on the encoder side . 
I've used it time ago , and you will have many errors of memory ( RAM ) . 
Remember it's a VM , not a dedicated server , ( down side is the best side ) , they scale . Witch makes your script doesn't know exacly what hardware is running on .

**Comment by tonuzo** [comment]
I see.. There probably is problems with the google cloud instance. I made a new installation to another google instance and the problem was still there. I also made a test instance to AWS EC2 and there was no problem with this...

**Comment by akhilleusuggo** [comment]
The purpose of using google cloud is not to be a ''normal VM'' . You're saying over 30euros/month for 1 core and 3gb ram , 100gb disk . Over priced on the eyes of any user for such low hardware . But the options that comes with it , API and all the list that are included ( software development ) , it is what makes it so expensive .
Does not match the purpose of this project , except for a dedicated live-streaming server with NGINX

**Comment by tonuzo** [comment]
Hey, I got it working! I was using php7.2-fpm, no good.
I enabled php7.2 and problem solved.
