### ISSUE TITLE
Encoder

### ISSUE THREAD

**Issue by phonocar** [WWBN/AVideo-Encoder#236]
Hello
The streaming site and the encoder works nickel
I download a mp4 file which is 6.0 MB on a streaming site that I ask to encode the encoder it goes from 6.0 MB to almost 35 MB in low resolution, normal?

google traslate

**Comment by akhilleusuggo** [comment]
change the ffmpeg encoder settings if you want to adjust bitrate

**Comment by phonocar** [comment]
thank you for this reponce but or that?
I see the tab "configuration" but I see not "bitrate"

**Comment by akhilleusuggo** [comment]
You can customize your encoder as you want . Just keep the `{$pathFileName}` and `{$destinationFile}`

Give you one example for 720p ( you can try it ) 
```
ffmpeg -i {$pathFileName} -vf scale=-2:720 -c:v h264 -movflags +faststart -minrate 920k -crf 23 -maxrate 3500k -bufsize 4500k -preset veryfast 
-c:a aac -b:a 128k -max_muxing_queue_size 1024 -y {$destinationFile}
```

**Comment by phonocar** [comment]
thank you akhilleusuggo for this answer
but i still have a little quetion
"I send fast" a video mp4 download on a streaming platform its do nothing at all "video automatucally booked

screen -> [https://cloud.laurent-david.fr/index.php/s/sZBmdgWGaRQKHDD](url)

**Comment by phonocar** [comment]
merci akhilleusuggo pour cette réponse
mais j'ai encore une petite quetion
"J'envoie rapide" une video mp4 telecharger sur une platforme de  streaming  sa faire rien du tout "video automatucally booked"

**Comment by akhilleusuggo** [comment]
@phonocar l'image fonctionne pas

**Comment by phonocar** [comment]
il faut fait un copier/coller de l'adresse

**Comment by akhilleusuggo** [comment]
I see that your video is uploaded . But looks like you have made a direct upload , not encoded 
Just to skip this , are you a cpanel user or any kind of panels ?

**Comment by phonocar** [comment]
I follow administrator of my sites for past time ;)

**Comment by akhilleusuggo** [comment]
Are you using any panel ? cpanel or other kind of panels ?

**Comment by phonocar** [comment]
Sorry i don't understand your question
