### ISSUE TITLE
chunk size

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#240]
How much is the ChunkSize ?
I can't find it anywhere . I just tacked the /videos/chunk and saw 5mb/request .
Where to change this value ?
And why so low when cloudflare allows up to 100mb

**Comment by DanielnetoDotCom** [comment]
I guess it is 1mb chunks, not sure why this value, I just keep the same value that was from the code sample.

You can find it here https://github.com/WWBN/AVideo/blob/a733058f83099803b5d508544b275626272fdc79/objects/aVideoEncoderChunk.json.php#L11

and here https://github.com/WWBN/AVideo-Encoder/blob/88be02f006ed5aaa139a43b1fda18f4365c3f2a9/objects/Encoder.php#L884

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Does this value work only when transferring data between encoder to stream , or also when trying a direct upload to the encoder ?

**Comment by DanielnetoDotCom** [comment]
The code lines I mention above are to transfer between encoder to stream

the codes to upload to the encoder are

https://github.com/WWBN/AVideo-Encoder/blob/ef55d9f4a4c9a7e11a325e1a1ba1ff7fb5a1df50/view/jquery-file-upload/js/main.js#L22

https://github.com/WWBN/AVideo-Encoder/blob/ef55d9f4a4c9a7e11a325e1a1ba1ff7fb5a1df50/view/jquery-file-upload/server/php/UploadHandler.php#L1190

**Comment by akhilleusuggo** [comment]
Those are the 5mb that I have mentioned .

> I can't find it anywhere . I just tacked the /videos/chunk and saw 5mb/request .

Thank you , I'll experiment by making it 50mb . Why ? Because the upload stops every 5mb , and does limit the upload speed so much . ( 50mbps )
