### ISSUE TITLE
Upload file size

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#243]
Can you please tell me in witch part of the script does detect the file size of the files of the direct upload ?

![image](https://user-images.githubusercontent.com/52116577/79828783-1ba99900-83aa-11ea-958c-a05ad62200e5.png)

**Comment by DanielnetoDotCom** [comment]
we use this script https://github.com/blueimp/jQuery-File-Upload/, maybe is better ask there

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom thanks , I found it here https://github.com/WWBN/AVideo-Encoder/tree/master/view/jquery-file-upload
