### ISSUE TITLE
again stuck on /tmp

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#246]
I'm not able to track or find it on the code source .
The last thing I find about it is : 
```
$obj = new stdClass();
$obj->file = tempnam(sys_get_temp_dir(), 'YTPChunk_');

$putdata = fopen("php://input", "r");
$fp = fopen($obj->file, "w");

```
Files stuck on tmp 
![image](https://user-images.githubusercontent.com/52116577/80274390-ab20b600-86e2-11ea-8726-4312f2e4fc84.png)

But where is the code source that executes the unzipping process ?
Can't find it on the hls source code neither . 

I want to keep tracking this issue , for that I would ask you something : 
When encoding fails on the transfer , add a button to just RE-SEND the zipped file , do not RE-ENCODE the entire file .Like the example below : 

![image](https://user-images.githubusercontent.com/52116577/80274438-0b175c80-86e3-11ea-9560-f3b972589a2d.png)

The file already encoded , no need to re-encode , I just want to re-send without re-encoding and wast time .
Re-queuing will make it re-encode and not re-send . This option should have 2 possibilities .
Re-queue :
1- If process is stuck at encoding = re-queue will retry to re-encode
2- If process is on transfer = re-queue will re-send/transfer to streamer .

**Comment by DanielnetoDotCom** [comment]
done

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Does re-send the file , but stuck at processing 
![image](https://user-images.githubusercontent.com/52116577/80292631-591e7580-8760-11ea-880d-5189a3247910.png)

**Comment by DanielnetoDotCom** [comment]
Can you please check what was the error in the encoder log file, so I can add a bypass to it?

I guess was something in the zip process.

**Comment by akhilleusuggo** [comment]
No , and no errors . It's sending , but when the process of sending is realizing , the ''bare processing '' get stuck .
And you can't reload the page or anything before you restart apache .
The script does his job by re-sending the zip , but is stuck at processing .

**Comment by DanielnetoDotCom** [comment]
I see, so what do you think I can do? remove this feature?
I cannot cancel the sending process. it will probably try to send it twice.

**Comment by akhilleusuggo** [comment]
just remove the pop-up ''Processing"

**Comment by DanielnetoDotCom** [comment]
it is not removing due to some JS error or some bad JSON response

I cannot test it from here, can you please check what error was that?

What JSON response are you getting? can you please provide the response?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'll experiment with home server .
I need sometime to encode something that could give me the error . 
I'll leave you one answer once I can get it stuck again .
