### ISSUE TITLE
H254 codec lower quality

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo-Encoder#248]
I am reaching out so as to find out how to make a change to codec H265 or HEVC. I know that FFMPEG has h265 as a dependency to make it work with my streamer.

My current setup makes my videos 3 times bigger and lower quality. 

can you guys help on this?

**Comment by akhilleusuggo** [comment]
h265 is not a supported on any browser ( html5 )

**Comment by ronaldod** [comment]
Correct. to support his statement look at [https://caniuse.com/#feat=hevc](https://caniuse.com/#feat=hevc)

**Comment by akhilleusuggo** [comment]
The only equivament to h265 that is supported on HTML5 is using the libvpx-vp9 codec .
It's a video compression by google ( webp project )

More info here https://developers.google.com/media/vp9

**Comment by ronaldod** [comment]
@daoguey Do you use the default settings for the converter or already changed the preset to medium ? Before the setting was ultrafast and that gave a huge file size. Medium is 10-15% slower but better compression results.

**Comment by daoguey** [comment]
Thank you all for the comments in such a short period of time! 

I was checking and testing the file in hevc the compression is awesome but it only works on edge ie and one more browser.

I will check the medium compresion vs ultrafast and do a -cfr 20 vs default. 

I will test this also with vp9 and see and play with different settings for best resolution.

Thank you all for the quick answers.

If you have a script for me to test from yojr encoders please send it over so i can also test it and see quality/speed performance.

Thank you

**Comment by akhilleusuggo** [comment]
crf 20 is not the best one . ofc you will have huge file size .
Recommended for online hosting site ( crf 23-26 )

**Comment by daoguey** [comment]
closing issue as i feel that I got an answer on this.

thank you all
