### ISSUE TITLE
Thumbnails generated by plugin are of low quality

### ISSUE THREAD

**Issue by anand0205** [WWBN/AVideo-Encoder#253]
Hi,

I have recently bought auto thumbnail generator. but the thumbnails I see in my app are of very low quality..is there any way to increase its resolution?

**Comment by ronaldod** [comment]
There are 2 plugins referring to thumbnails. `Video Thumbnails` and `MP4ThumbsandGif`. And ad also a screenshot so we can also see if it this "normal" behavior.

**Comment by anand0205** [comment]
Hi,

I am seeing this with MP4 uploads too, and that plugin is for MP4..I have
attached screenshot.

**Comment by ronaldod** [comment]
Please post the screens on github . Use the `view it in GitHub` link in the email.

**Comment by anand0205** [comment]
![Screenshot_2020-05-11-20-07-08-14_24e593c7bba62d63c6beb65449d4de2b](https://user-images.githubusercontent.com/65141985/81587542-cc68ee00-93d4-11ea-9554-a004f9386394.jpg)

**Comment by DanielnetoDotCom** [comment]
You can now customize the thumbs size

![image](https://user-images.githubusercontent.com/18009293/81602311-b93d2a80-93a2-11ea-9797-e3d30fab54d2.png)

**Comment by DanielnetoDotCom** [comment]
Also, you can delete the thumbs from a video. it will be regenerated

![image](https://user-images.githubusercontent.com/18009293/81602373-de319d80-93a2-11ea-9883-3fb44a55e348.png)

**Comment by anand0205** [comment]
Hi Daniel,
I don't see these options. I have attached screenshots, Please let me know if I need to upgrade anything. Thanks.
![Capture4](https://user-images.githubusercontent.com/65141985/81631186-efbb8980-9424-11ea-9a05-632382c621a1.PNG)
![Capture3](https://user-images.githubusercontent.com/65141985/81631192-f0ecb680-9424-11ea-84a3-c956daa3a1b3.PNG)
![Capture1](https://user-images.githubusercontent.com/65141985/81631195-f1854d00-9424-11ea-9bff-d25e3b3edf79.PNG)
![Capture2](https://user-images.githubusercontent.com/65141985/81631198-f21de380-9424-11ea-828c-c3e3f8ac8bfa.PNG)

**Comment by akhilleusuggo** [comment]
I think you need to re-download the plugin

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom What dimension are recommended ? Will this change the size of what exactly ?
The first page thumbnails ? What if you increase the size ? Will it lose responsiveness ?

**Comment by DanielnetoDotCom** [comment]
I am not sure what should be the best size yet, **(I accept ideas)**

But that is how works ...

when you encode a video it will generate a 640x360 px image poster (displayed on big video)
but this is too much to display on the front page, so by default, we create a new image file with 250 x 140 px, and that is the one we display in the rows (default 6 videos per row).

Some times the rows are smaller and the responsive layout show fewer items per row, for example in the mobile it shows only one item per row, so the image gets bigger and you can see the low quality

If someone gets the ideal size, please let me know.

**Comment by anand0205** [comment]
And Daniel that options..As i said i dont see that..does i need to change anything or upgrade anything??

**Comment by DanielnetoDotCom** [comment]
@anand0205 as @akhilleusuggo said, you just need to update your code.

Thar is how to do https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Taking a look at the youtube's one , is using 720x404

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo but that is the main one, I am talking about the small ones 
![image](https://user-images.githubusercontent.com/18009293/81861194-3d77e500-953e-11ea-986e-8d7676327205.png)
maybe we should use 420x270 px

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom ofc , I'm talking about the original files . The small once will depend of the screen resolutions . I'll try 420x270

**Comment by akhilleusuggo** [comment]
The resize doesn't start after changing the resolutions .
I'll have to take a look at the code , but when creating a video , an image should be created at the maximum resolution of the video and stored ( to never delete ) .

So when admins changes the resolutions , the files `thumbsSmallV2` should be deleted , and recreated when the pages loads .

Images usually are created from `_YPTuniqid_ID.jpg` , then resized and received with the name `_YPTuniqid_ID_thumbsSmallV2.jpg`

**Comment by DanielnetoDotCom** [comment]
Right now we have a button to delete the thumbs one at a time 

![image](https://user-images.githubusercontent.com/18009293/82051123-b20e6900-968f-11ea-8264-fc89ff8b3337.png)

but you can delete all thumbs at the videos site (Careful to not delete the videos)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No daniel , that button is to remove thumbs generated from Plugin VideoThumbnails (VideoThumbnails)

**Comment by DanielnetoDotCom** [comment]
This button executes this method that deletes all the thumbs 
https://github.com/WWBN/AVideo/blob/d655f8ca3ef9ae20dd58a1e60814f2b1aa06f931/objects/video.php#L2990

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you add an option '' delete all the thumbs of all videos '' ?

This could take too much clicks to delete all .

**Comment by DanielnetoDotCom** [comment]
What about this, I made a command-line tool.

In your terminal go to the installation directory and type `php deleteThumbsFiles.php`
this will remove all thumbs

**Comment by akhilleusuggo** [comment]
Thank you ;)
