### ISSUE TITLE
Same Issue Unable to Get Encoder To Point to Local Server for Encoding

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo-Encoder#259]
Final Issue No:3:

Hi Daniel,

Kindly take a look at the attachment as may I ask when clicking this link what should happen? As it reroutes to your online encoders but we want it to use the "local" server where we installed the encoder on. How is this supposed to work as I have searched the available docs and I am unable to deduce  this info in anyway.  Right now when we click it it gives us the "SORRY....This Streamer site is not allowed" and we see in the URL it is trying to go to your encoder (encoder2.avideo.com). In the configuration we have "disabled" it from doing that so it should not even be "trying" in the first place as it seems that is hard-coded somewhere else besides the configuration page.

Thanks
Fuquan

![EncoderIssueStill](https://user-images.githubusercontent.com/17571557/82151520-23027c00-985c-11ea-85d2-cd199119445f.JPG)

**Comment by ronaldod** [comment]
Please post in the right repository. And review mine comment to set the encoder correct. As it still pointing to the public encoder. And if you installed the encoder local you have something created in directory on your server. so it would be like https://yoursite.com/encoder. Where encoder is the subfolder where you installed the encoder.

**Comment by Fuquan999** [comment]
Thanks for that but trust me I tried that even the very first time some days back as I deduced that should be the order of the Folder/files it needs but that did not work. But now that we have resolved one issue with cache let me go try it and see on that when I login. Will update in a while

**Comment by Fuquan999** [comment]
Prior to this I hit that Clear Cache Directory tens of times it did not work but it needed the one you mentioned "Clear First Page Cache": Unfortunately, although it is now taking/saving the entry of the address (as it would not save it in the past) I have just tried the "Encoder" link but it still tries to go to your server2. But lets give it a while as I suspect it may be related to the cache again because like I said it would not save in the past and now it has started to save so it may redirect properly.


![LetsWait](https://user-images.githubusercontent.com/17571557/82152724-98be1600-9863-11ea-81f5-b5a3d8708dbb.JP

**Comment by DanielnetoDotCom** [comment]
@Fuquan999 what do you have here?

![image](https://user-images.githubusercontent.com/18009293/82205341-d3b06000-98dc-11ea-8250-1f547799e4fc.png)

And here?

![image](https://user-images.githubusercontent.com/18009293/82205400-ef1b6b00-98dc-11ea-85d6-2b03f7a384a9.png)

Please screenshot your side so we can guide you how to have a correct configuration

**Comment by Fuquan999** [comment]
I forgot to close this particular ticket as I informed you in the other issue (caching issue) that it had started working so this is no longer a problem as it was related to the "First Page Cache" thing.

I will close this ticket
