### ISSUE TITLE
Chat and Webcam Issues

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo-Encoder#260]
Hi Daniel,

Maybe this is related to the ongoing issue of where clicking does nothing (user Edit button) as the Chat semes not to be working as you can type but no "Enter" when you click the button or press the enter key. The same goes for the minimize (white circled down arrow) button that does not work as the chat window does not minimize in any way even when set to default of  "startMinimized" on load. Not even the "attachment" on the chat works as that too is dead. Similarly the webcam thing is not working as it just says "loading Webcam". The "Live" video is the motivation for us getting the plugins and app in the first place so figuring this one out is top on our list.

The good news is that the "encoder" is now routing properly when you click the "encode video and audio" link.

Also may I ask what does the "Menu" plugin do as it does not have a way to "Link" to any page internal or external? (See image)

Thanks Fuquan

![Chat and WebCam Challenge](https://user-images.githubusercontent.com/17571557/82157045-67ebda00-987f-11ea-8165-4ce123b5e605.JPG)

![MenuWhatDoesItDo](https://user-images.githubusercontent.com/17571557/82157097-be591880-987f-11ea-93fe-57284eac1007.JPG)

**Comment by ronaldod** [comment]
Wrong place to ask. Go to [Avideo's issues](https://github.com/WWBN/AVideo/issues) not Avideo-encoder. Please read my previous comments about this.
