### ISSUE TITLE
git faill

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo-Encoder#262]
git pull
error: object file .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02 is empty
error: object file .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02 is empty
fatal: loose object 693374fca2b5371b1b1272896eb2345b93f45f02 (stored in .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02) is corrupt
fatal: The remote end hung up unexpectedly
root@mysqltube-virtual-machine:/var/www/html/AVideo-Encoder# sudo git fetch --all && sudo git reset --hard origin/master
Fetching origin
error: object file .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02 is empty
error: object file .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02 is empty
fatal: loose object 693374fca2b5371b1b1272896eb2345b93f45f02 (stored in .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02) is corrupt
fatal: The remote end hung up unexpectedly
error: Could not fetch origin
root@mysqltube-virtual-machine:/var/www/html/AVideo-Encoder# sudo git fetch --all && sudo git reset --hard origin/master
Fetching origin
error: object file .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02 is empty
error: object file .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02 is empty
fatal: loose object 693374fca2b5371b1b1272896eb2345b93f45f02 (stored in .git/objects/69/3374fca2b5371b1b1272896eb2345b93f45f02) is corrupt
fatal: The remote end hung up unexpectedly
error: Could not fetch origin
What do we fix this problem ?

**Comment by ronaldod** [comment]
your local git settings are corrupt. Not funny.   Search google for fatal: "loose object" and "corrupt".

**Comment by hnagasawa** [comment]
Thank you for your support.
