### ISSUE TITLE
Sorry! We could not find your streamer site!

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo-Encoder#263]
Hi,

I search and tried everything I could find and not having any luck.

**Ubuntu 18.04 Fresh Install with Apache**

Streamer and Encoder installed without any issues.  I can login to Stream no problem, but when I try to login to Encoder I get "Sorry! We could not find your streamer site!"
I followed these instructions **"https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server"** for both Apache and NGinX and having the same issue with both.  Only thing I changed in this install was I installed MariaDB 10.2 as I noticed someone said they had the same issue with 10.1, didn't fix it for me.  I probably did a fresh install 8 to 10 times now trying different options. :)

I cleared the /var/www/YouPHPTube/upload/videos/avideo.log and tried to login here is the results.
[18-May-2020 22:41:23 America/Halifax] https://www.MYDOMAIN.ca/ == https://www.MYDOMAIN.ca/
[18-May-2020 22:41:23 America/Halifax] login.json: Login::run
[18-May-2020 22:41:23 America/Halifax] Login::run (admin, ***, https://www.MYDOMAIN.ca/, true)
[18-May-2020 22:43:28 America/Halifax] Get Login fail, try again
[18-May-2020 22:45:28 America/Halifax] Error on Login context
[18-May-2020 22:45:28 America/Halifax] https://www.MYDOMAIN.ca/login

/var/log/apache2/youphptube.error.log after rebooting the server.
[Mon May 18 23:22:24.513604 2020] [proxy_fcgi:error] [pid 1765] [client MY-IP-ADDRESS:60953] AH01067: Failed to read FastCGI header, referer: https://www.MYDOMAIN.ca/upload/
[Mon May 18 23:22:24.513686 2020] [proxy_fcgi:error] [pid 1765] (104)Connection reset by peer: [client MY-IP-ADDRESS:60953] AH01075: Error dispatching request to : , referer: https://www.MYDOMAIN.ca/upload/
[Mon May 18 23:23:10.087679 2020] [proxy:error] [pid 1464] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.sock (*) failed
[Mon May 18 23:23:10.094198 2020] [proxy_fcgi:error] [pid 1464] [client MY-IP-ADDRESS:61169] AH01079: failed to make connection to backend: httpd-UDS, referer: https://www.MYDOMAIN.ca/
[Mon May 18 23:23:10.609117 2020] [proxy:error] [pid 1463] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.sock (*) failed
[Mon May 18 23:23:10.609163 2020] [proxy_fcgi:error] [pid 1463] [client MY-IP-ADDRESS:61168] AH01079: failed to make connection to backend: httpd-UDS, referer: https://www.MYDOMAIN.ca/

/var/log/apache2/error.log after rebooting the server.
[Mon May 18 23:22:24.565629 2020] [mpm_prefork:notice] [pid 1451] AH00169: caught SIGTERM, shutting down
[Mon May 18 23:23:09.606369 2020] [mpm_prefork:notice] [pid 1461] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Mon May 18 23:23:09.815016 2020] [core:notice] [pid 1461] AH00094: Command line: '/usr/sbin/apache2'

Encoder URL is:
https://www.MYDOMAIN.ca/upload

Streamer Site is set to:
https://www.MYDOMAIN.ca/

URL's in Encoder Database are also set to HTTPS.

I set these options in PHP.ini with no luck
allow_url_fopen = On
allow_url_include = On

Thank you for any help...

Folder Permissions are attached.
![Permissions](https://user-images.githubusercontent.com/65576427/82276192-f3866900-995a-11ea-9f74-f0b4488d1f84.png)

**Comment by akhilleusuggo** [comment]
check that your hostname is correct .
I had this issue before and the hostname was the cause

**Comment by D-Spayre** [comment]
WoW thank you very much.  That worked...

Anyone else with the same issue here is what I changed.
sudo hostnamectl set-hostname www.MYDOMAIN.ca

sudo nano /etc/hosts
127.0.0.1     www.MYDOMAIN.ca

Thanks again

**Comment by akhilleusuggo** [comment]
I would recommend you NOT to use on your hostname a ''real domain name '' , but something like server.myserver.com ( should not match your actual domain names used on your vhosts ) , that would confuse the server's connections .

Daniel should add this to the Wiki. It took me 2 days to find out about this .
The solution below are deprecated : 
```
allow_url_fopen = On
allow_url_include = On
```
