### ISSUE TITLE
Can't click upload options

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#266]
![image](https://user-images.githubusercontent.com/52116577/82650419-590c7b00-9c23-11ea-8687-a06cc0cd8f5d.png)

Can't click on Start Upload , Cancel Upload nor Delete .
Also the +Add files I'm having hard time to click .

Can anyone confirm it ? ( with latest update )

**Comment by ronaldod** [comment]
#265 had a change.
Propesed a new one.

To place 

```
            <input type="checkbox" class="toggle" name="selectAll" >
            <label for="selectAll"> Select All </label>

```

instead of:
```
            <div class="checkbox">
                <label><input type="checkbox" class="toggle"> Select All</label>
            </div>
```
That should bring back in line.

**Comment by DanielnetoDotCom** [comment]
Thanks, like this?

**Comment by ronaldod** [comment]
Did a new pull and the buttons works again.

**Comment by akhilleusuggo** [comment]
Works , thanks
