### ISSUE TITLE
domain/upload page throwing following error-route not found

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo-Encoder#267]
Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/" in /home3/vraghavans/public_html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300 Stack trace: #0 /home3/vraghavans/public_html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest() #1 /home3/vraghavans/public_html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start() #2 {main} thrown in /home3/vraghavans/public_html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300

Please advise,the site sits on hostgator in shared space,site url seafarerstube.com

**Comment by DanielnetoDotCom** [comment]
you probably do not have the mod-rewrite enabled.

**Comment by vraghavans** [comment]
yes fixed,thanks so much
