### ISSUE TITLE
Chunk retries 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#276]
Where to change the number of retries before the using the traditional transfer ( in the code )

**Comment by DanielnetoDotCom** [comment]
this is hardcoded here https://github.com/WWBN/AVideo-Encoder/blob/5c94f3af32eadb768a95b31820bd034fc0cefa97/objects/Encoder.php#L911

**Comment by akhilleusuggo** [comment]
THANKS !!! Was looking for that like the entire week xD
