### ISSUE TITLE
streamer's home page

### ISSUE THREAD

**Issue by munenejosef** [WWBN/AVideo-Encoder#284]
I am getting a blank page after deleting streamer's installation directory. When I get to the main page it's all blank.

**Comment by DanielnetoDotCom** [comment]
humm, I am not sure the reason. check the log file.

or try just to copy it back and see if will come back to work.

**Comment by munenejosef** [comment]
Hey Daniel. It worked. I guess it was an issue with memory. Thanks a lot for the support.
