### ISSUE TITLE
How can I add subtitles to my movie?

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo-Encoder#287]
How can I add subtitles to my movie?  option in the player, turn on subtitles. defaults to no subtitles

**Comment by DanielnetoDotCom** [comment]
You need the SubtitleSwitcher from https://youphp.tube/marketplace/

![image](https://user-images.githubusercontent.com/18009293/91341014-4750eb80-e7af-11ea-991d-461467073de0.png)

**Comment by awistudio** [comment]
ok i already bought and installed it, but how to add subtitles

**Comment by DanielnetoDotCom** [comment]
Make sure you install the tables and go to your videos manager

![image](https://user-images.githubusercontent.com/18009293/91343511-0b1f8a00-e7b3-11ea-8a7e-c3b66e557507.png)

**Comment by awistudio** [comment]
![2020-08-26_20-50-41](https://user-images.githubusercontent.com/60708776/91344209-ec82b880-e7dd-11ea-8d4e-a1017953279b.png)
install tables - this option is missing

**Comment by DanielnetoDotCom** [comment]
Sorry, you are correct, the SubtitleSwitcher does not require tables

**Comment by awistudio** [comment]
I don't know what you did but there are subtitle options :)

**Comment by DanielnetoDotCom** [comment]
Sorry what?

**Comment by awistudio** [comment]
ok, i have subtitle options, but there is a problem with the write. I create subtitles but do not add to the movie
![2020-08-26_21-07-26](https://user-images.githubusercontent.com/60708776/91345863-50a67c00-e7e0-11ea-9e78-f475d96b8c23.png)

**Comment by DanielnetoDotCom** [comment]
Check if the `videos/*.vtt` subtitle file was created 

try to clear your site cache

**Comment by awistudio** [comment]
![2020-08-26_21-13-50](https://user-images.githubusercontent.com/60708776/91346453-2903e380-e7e1-11ea-99de-b7419d703549.png)
does not save the file. no editing.

**Comment by DanielnetoDotCom** [comment]
make sure you select a language.

click in save.

if does not save the .vtt file check the log file

**Comment by awistudio** [comment]
I already have a .vtt file.
but no editing option appears, only upload or create
![2020-08-26_22-10-12](https://user-images.githubusercontent.com/60708776/91351682-fc53ca00-e7e8-11ea-8cf4-12f29628ae88.png)

**Comment by awistudio** [comment]
can I set ANOTHER icon?  SUBTITLES. just like the sound. ON OFF SUBTITLES
![2020-08-26_22-15-24](https://user-images.githubusercontent.com/60708776/91352428-22c63500-e7ea-11ea-9f7d-1f80f35d9fed.png)

**Comment by DanielnetoDotCom** [comment]
When you click on create subtitle you can edit it.
That icon is the videojs default one. probably you can change it with CSS

**Comment by awistudio** [comment]
ok Daniel. but after saving I can't load them for improvement.

**Comment by DanielnetoDotCom** [comment]
Click in create subtitle and then select the language you want to edit. The subtitle will load

**Comment by awistudio** [comment]
![2020-08-26_22-15-244444](https://user-images.githubusercontent.com/60708776/91412864-a0ba2880-e84a-11ea-9a4a-8573bd2c3ce7.png)
I cannot find the file. where can this be changed?

**Comment by DanielnetoDotCom** [comment]
I just made this video https://tutorials.avideo.com/video/84/subtitleswitcher-plugin-usage

In this video, I upload a set file and then edit it.

The same way I edit you can use to create other languages

**Comment by awistudio** [comment]
Hi

can only admin add subtitles?
how to set the user to add subtitles?

**Comment by awistudio** [comment]
such a message
![2020-09-22_21-33-16](https://user-images.githubusercontent.com/60708776/93928911-59c13500-fd1b-11ea-8c02-2f9d639356b8.png)

**Comment by awistudio** [comment]
how to solve the problem? please help
adding subtitles by any user

**Comment by DanielnetoDotCom** [comment]
Please open an issue on AVideo NOT on encoder

Provide details of step by step of what you are doing and also provide the log files
