### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#288]
@DanielnetoDotCom Daniel if you remember before we've always had this issue where the same file is encoded multiple time like the this example below .

How did you fixed it ? What was the issue ? because I don't see it anymore .

It's definitely something related to this line  : `_session_start();` and the log start session and end session .

Just wanted to know .

**Comment by DanielnetoDotCom** [comment]
LOL, to be honest, I have no idea.

Maybe I fixed something else that was bringing this problem

**Comment by akhilleusuggo** [comment]
Thanks anyway , I don't see it anymore in the last month
