### ISSUE TITLE
my site ban?

### ISSUE THREAD

**Issue by bumbifyllan** [WWBN/AVideo-Encoder#290]
whay are my site baned on my own encoder ?
![231231](https://user-images.githubusercontent.com/70781203/92289403-a54ca400-ef10-11ea-9048-1d2b09283198.PNG)

**Comment by DanielnetoDotCom** [comment]
Probably due Porn content

**Comment by bumbifyllan** [comment]
No you can lock it self http://sturescykelverksta.com/master

**Comment by DanielnetoDotCom** [comment]
you probably removed it by now, but I can see porn was detected in your site.

**Comment by bumbifyllan** [comment]
I promise I have not uploaded anything like that but the page has been open for everyone to register and upload but have not found anything like that myself but now the page is locked for others to register and please you can not block up with my domain sturescykelverksta .com

**Comment by DanielnetoDotCom** [comment]
The site is unbanned now

**Comment by bumbifyllan** [comment]
Ok THX you are THE best
