### ISSUE TITLE
Upload files in Encoder failed with Javascript error

### ISSUE THREAD

**Issue by olivierDM40** [WWBN/AVideo-Encoder#291]
After migration to Avideo 9.5 and Avideo-Encoder 3.2 t, the Encoder now fails to upload and convert files. 
No file is saved on server side, and no queue is created.

Debug mode in browser show a javascript error with the error message : 
msg: "Error on rename(/var/www/html/YouPHPTube-Encoder/videos/chunk/1/test.mp4, /var/www/html/YouPHPTube-Encoder/videos/original_test_YPTuniqid_5f57b5ed47b469.48658793)"

After investigation on server side, no folder "chunk" exists into videos directory
videos directories for AVideo and Avideo-encoder are both in 777 mode 

No avideo.log or avideo-encoder.log are generated ... i've deleted them before restarting apache, and after error raised, no log have been generated again

But, in Apache error_log file, some error messages are displayed with a permission problem on Configuration.php file line 108 (when this script try to rewrite the configuration.php file to match with the new format and entries)

I verified the permission of videos/configuration.php file and it's in 777 mode

I supposed that the videos/configuration.php file must be regenerated to fulfit a new format for the new version of encoder (i saw that 2 or 3 entries ares created, and maybe a change of booleans into integers for specific properties ? ), but it fails, and maybe implies somes problems on all the cascade of treatments.

I made a test to check if, by creating chunk directory manually, it could solve the problem ? but not ... 
Maybe a quick test to investigate if the problem came from a bad videos/configuration.php file for encoder, could be  to copy paste a new configuration.php file manually at the new format ... but i don't have any example of such file ... 

Thank you for your help 
Olivier 
[issueavideoencoder.zip](https://github.com/WWBN/AVideo-Encoder/files/5190898/issueavideoencoder.zip)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is happening. but I guess the best solution would be, reinstall the encoder;

Just delete the configuration.php file and drop the database and run the installation again. the script will create the configuration.php file with the correct permissions

**Comment by olivierDM40** [comment]
So, my problem is solved, not by reinstalling encoder, but by authorizing in SELinux the web server to modify all files under videos directory.
By default, in redhat distribution, SELinux block these updates, even if subfolders are in 777 mode. 
The command line to add the missing permissions : 
sudo chcon -R -t httpd_sys_rw_content_t /var/www/html/YouPHPTube/videos

After adding this rights, the configuration.php file have been correctly regenerated by webserver, and everything works fine, my encoder reencode properly
Thank you
