### ISSUE TITLE
Header And Sidebar Ads Overlapping After New Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo-Encoder#300]
I updated my site and now the header and sidebar ads are overlapping, making a mess of things. I have paid ads here so this is an urgent issue. It was working perfect before the update.

I see the same issue with chrome and firefox.

I am using "Gallery" mode.

Attached is a screen shot of the issue.

![Ads-Overlapping](https://user-images.githubusercontent.com/45924889/99429482-17107900-28d6-11eb-8667-cd56b3bc03d5.png)

**Comment by DanielnetoDotCom** [comment]
you need to make your images responsive.

on bootstrap you should create image tags like this...

`<img src="..." class="img img-responsive"/>`

add the class in your img tag and you should be fine

**Comment by The-Do-It-Yourself-World** [comment]
Thank you. That fixed it.
