### ISSUE TITLE
get_ffprobe() is missing from objects/functions.php

### ISSUE THREAD

**Issue by sizious** [WWBN/AVideo-Encoder#307]
The latest commit broke the encoding process because the `get_ffprobe()` function is missing from the `objects/functions.php`.

To fix that, please add the following to the file:

```
function get_ffprobe() {
    return 'ffprobe ';
}
```

Thank you for your tool, it's a great product! Keep up the good work!

**Comment by DanielnetoDotCom** [comment]
I am so sorry, I missed that update.

here it is

**Comment by sizious** [comment]
No problem! Thank you very much for your fast answer!
Cheers!
