### ISSUE TITLE
Processing does not start.

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo-Encoder#312]
It is a new installation, do you have any idea how this error occurs.

![image](https://user-images.githubusercontent.com/52116237/104116858-a0638b00-531c-11eb-9ed6-af956ee7fdec.png)

**Comment by DanielnetoDotCom** [comment]
Please google for this error and you will find a solution

**Comment by Donnerstein** [comment]
Sorry, it was actually my fault.
