### ISSUE TITLE
Slow Upload on native encoder

### ISSUE THREAD

**Issue by itpastor** [WWBN/AVideo-Encoder#316]
Hello.  I have a fresh install of AVideo Streamer + Encoder on a powerful VPS call that server A.  
Server A Specs:  8Core, 16GB Ram, Approx 100mbit/s 240GB HD
Server B Specs  4Core, 4GBRam, Approx 30mbit/s  80GB HD

I noticed that when uploading & encoding videos entirely to AVideo encoder (Server A) the speed is VERY slow.  However when I switch to a different Encoder (Server B Encoder) connected to Streamer on Server A the speed is much faster to upload and then encode.  Keep in mind encode speed is faster on Server A, however upload speed is slow, unless I use the non-native encoder on server B with the streamer on server A..  I have checked the speed on both servers and both machines used to upload and they are 50mbit+

I would like to use only Server A to do all Encoding and Streaming, but its 3X slower just to upload.  Encoding is sufficient, but upload drags.
Any ideas?
![Avideo Speed_Question](https://user-images.githubusercontent.com/40804331/105048046-1a8cc180-5a39-11eb-95d1-f1f2a6b92fb2.png)

**Comment by akhilleusuggo** [comment]
Nothing to do about this .
TCP/location limitation/issues .

Get a server closer to your country .

**Comment by itpastor** [comment]
Sorry - I was not clear.  Upload speed is not the issue.  Issue: Server A Encoder to Server A Streamer completes slowly.  Server B Encoder to Server A streamer finishes MUCH more quickly, even though Server B has fewer resources.

![Avideo Speed_Question2](https://user-images.githubusercontent.com/40804331/105058914-ba9c1800-5a44-11eb-9268-414deca5b9f6.png)

**Comment by akhilleusuggo** [comment]
If I understand you well , your issues is When the Encoder is sending the encoded video to the streamer , right ?

Is the same , probably they're not close to each other .

EDIT ; 

Hold on , what I see is server A to A are both on the same server right ?
Then you need to bypass the public IP and use the internal IP for maximum performance . Normal servers will reach 10-15Gb/s

go to /etc/hosts

add your real domain names there ( without http/https protocols ) . Don't modify anything if you don't know what you doing , just add what you may be missing .   

Example ;

`sudo nano  /etc/hosts`

```
127.0.0.1       localhost
127.0.0.1       myserver.test.com     #hostname
12.12.12.12   encoder.test.com      encoder
12.12.12.12   streamer.test.com     streamer
```

**Comment by itpastor** [comment]
That worked beautifully!  Now time to complete the upload was doubled.  Thank you!
