### ISSUE TITLE
Wasabi & Amazon S3 Plugin

### ISSUE THREAD

**Issue by itpastor** [WWBN/AVideo-Encoder#317]
Hello!
Is it possible to use the Amazon S3 storage plugin but with Wasabi storage? I have searched online, and the forums but I haven't seen anyone attempt this.
Thanks,

**Comment by DanielnetoDotCom** [comment]
Yes it is posible https://github.com/WWBN/AVideo/wiki/How-do-I-use-the-AWS-S3-plugin-with-Wasabi

**Comment by itpastor** [comment]
Thank you!  Those settings allowed me to connect to Wasabi.  One issue though is that newly uploaded videos just spin when we attempt to play them.  see:  https://uhctube.com

I do see the videos in the wasabi bucket though

**Comment by itpastor** [comment]
Actually it's resolved now.  I found that useS3DirectLink must be checked.
Thank you!
