### ISSUE TITLE
What's the recommended parameters to improve MP4 videos quality?

### ISSUE THREAD

**Issue by sizious** [WWBN/AVideo-Encoder#318]
My question is really stupid but I can't get a good video quality when I send a MP4 video on the platform.
I'm aware of the `ffmpeg` tool used in background and I tried to improve the quality by changing the settings of the `Dynamic MP4` field:

```
-vf scale=-2:{$resolution} -movflags +faststart -c:v libx264 -preset ultrafast -crf 18 -pix_fmt yuv420p -acodec aac -strict -2 -b:a {$autioBitrate}k  -max_muxing_queue_size 1024 -y {$destinationFile}
```
I don't know what I need to change, because even if I use the important `crf` parameter with a low value, the quality is never good. When I use the max value (`51`, but I tried with `50`), the quality is horrible (as expected) so this parameter seems to be working. The default value is `23`, and in the [official documentation](https://trac.ffmpeg.org/wiki/Encode/H.264), it says that `18` is nearly lossless. But the quality is not so good. The image seems to be blurred.

Plus, even if I setup true lossless by putting `crf` to `0`, the video won't play in the `videojs` player.
Do you have some tips to improve the video quality?

Thank you very much.
This is related to https://github.com/WWBN/AVideo-Encoder/issues/123.

**Comment by sizious** [comment]
I forgot to say, if I use the "embed video" option (instead of uploading a video), the videojs player is capable of rendering the video and in a really great quality, near the quality on the computer. So this is related to `ffmpeg`.

**Comment by akhilleusuggo** [comment]
-preset ultrafast , change this to `-preset veryfast` at the least , crf 23 is good value .

This would be enough

**Comment by sizious** [comment]
OK I understood what's going on.
It isn't related to ffmpeg. Everything is OK in this side.

The issue is the videojs and multisource files. In the free version with no quality selector, the first source is taken into account in a random way. The function responsible of this "issue" is the `getSources()` function. The `$files` variable associative array is filled in a random way. In my case, the 240p version was always taken instead of my 1080p version, that's why I have this poor quality.

I'll suggest to add somewhere a default quality selector if the quality plugin selector is not available. What do you think @DanielnetoDotCom?

Finally, this issue has nothing to do with the encoder itself which works perfectly.

**Comment by akhilleusuggo** [comment]
@sizious you should just don't encode the video into multiple sources .

Go to plugins , and remove all exacept the quality that you wanna transcode (CustomizeAdvanced) , this way you save a lot of space and time encoding ;

![image](https://user-images.githubusercontent.com/52116577/105560852-b78f7900-5d1d-11eb-99f4-e35efdbcacdf.png)



Select all except the ones in red , should solve the problem . Clear the cache to see new option on encoder side  .

**Comment by sizious** [comment]
Thank you @akhilleusuggo, I changed the CustomizeAdvanced settings like below:

![avideo-encoder-settings](https://user-images.githubusercontent.com/15776845/105578942-f35d2980-5d83-11eb-8ce2-027be4145e7c.png)

But AVideo-Encoder still generate low resolutions videos. The 240p video is the first one and because of this, the quality is horrible. Is there something else to do for disabling low video encoding?

**Comment by sizious** [comment]
I finally managed this by using a custom JS in the page:
```
const videoResolution = 720;
let element = document.querySelectorAll("source");
if (element && element.length) {
  var hdSrc;
  element.forEach(function(item) {
	  if (item.src.toLowerCase().lastIndexOf("_" + videoResolution + ".mp4") != -1) {
		  hdSrc = item.src;
	  }
  });
  if (hdSrc) {
	  console.log("Setting up video resolution", videoResolution);
	  videojs.getPlayer("mainVideo").src({
		src: hdSrc,
		type: 'video/mp4'
	  });
  }
}
```
In the page, all videos sources are added in the `video` tag automatically by the AVideo platform, and now in the current release, the sources are sorted from the smaller (`240`) to the higher (e.g. `1080` or more) resolutions. This JS snippet will just replace the `videojs` source by only one configured in the `videoResolution` constant.
