### ISSUE TITLE
List Users and Streamers is Blank after update 3.5

### ISSUE THREAD

**Issue by lerd2805** [WWBN/AVideo-Encoder#341]
Hi i have noticed that the list where the users and streamer appear remains blank and I did not save changes in the encoder configuration either.

![screencapture-dreamax-tv-encoder-1613160635599](https://user-images.githubusercontent.com/31492754/107817446-1f951600-6d44-11eb-8d1a-6c87d4050bf4.png)

**Comment by DanielnetoDotCom** [comment]
please check the log files

**Comment by DanielnetoDotCom** [comment]
I have sent an update to the encoder, please check it

**Comment by lerd2805** [comment]
Is working now, thx @DanielnetoDotCom
