### ISSUE TITLE
does not encode 1080p/1440p/2160p

### ISSUE THREAD

**Issue by Sandra-UwU-neko** [WWBN/AVideo-Encoder#354]
hey i just made a fresh install of ur software

the problem is i cant encode higher than 720p 
![image](https://user-images.githubusercontent.com/23656101/110480290-9ffe2b00-80e6-11eb-875f-65b8ddbe8135.png)
![image](https://user-images.githubusercontent.com/23656101/110480416-c623cb00-80e6-11eb-9edb-12f8011523dd.png)

tell me what u need log wise etc. 
version is current git master branch

**Comment by DanielnetoDotCom** [comment]
If you are downloading from youtube we cannot guarantee it will download the 4K

we always try to download the highest resolution as possible but we depend on youtube-dl 

If you manually upload a 4K video it must generate the 4K one

**Comment by DanielnetoDotCom** [comment]
NOT to download, we auto-detect the format to encode.

again to download we depend on youtube-dl

**Comment by Sandra-UwU-neko** [comment]
`[info] Available formats for LXb3EKWsInQ:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus @ 50k (48000Hz), 1.89MiB
250          webm       audio only tiny   67k , webm_dash container, opus @ 67k (48000Hz), 2.53MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 4.84MiB
251          webm       audio only tiny  132k , webm_dash container, opus @132k (48000Hz), 4.96MiB
278          webm       256x144    144p   90k , webm_dash container, vp9@  90k, 30fps, video only, 3.38MiB
160          mp4        256x144    144p   96k , mp4_dash container, avc1.4d400c@  96k, 30fps, video only, 3.61MiB
330          webm       256x144    144p60 HDR  212k , webm_dash container, vp9.2@ 212k, 60fps, video only, 7.96MiB
242          webm       426x240    240p  184k , webm_dash container, vp9@ 184k, 30fps, video only, 6.89MiB
133          mp4        426x240    240p  214k , mp4_dash container, avc1.4d4015@ 214k, 30fps, video only, 8.03MiB
331          webm       426x240    240p60 HDR  445k , webm_dash container, vp9.2@ 445k, 60fps, video only, 16.65MiB
243          webm       640x360    360p  343k , webm_dash container, vp9@ 343k, 30fps, video only, 12.85MiB
134          mp4        640x360    360p  443k , mp4_dash container, avc1.4d401e@ 443k, 30fps, video only, 16.60MiB
332          webm       640x360    360p60 HDR  954k , webm_dash container, vp9.2@ 954k, 60fps, video only, 35.72MiB
244          webm       854x480    480p  619k , webm_dash container, vp9@ 619k, 30fps, video only, 23.18MiB
135          mp4        854x480    480p  845k , mp4_dash container, avc1.4d401f@ 845k, 30fps, video only, 31.61MiB
333          webm       854x480    480p60 HDR 1847k , webm_dash container, vp9.2@1847k, 60fps, video only, 69.11MiB
247          webm       1280x720   720p 1255k , webm_dash container, vp9@1255k, 30fps, video only, 46.97MiB
136          mp4        1280x720   720p 1649k , mp4_dash container, avc1.4d401f@1649k, 30fps, video only, 61.69MiB
302          webm       1280x720   720p60 2039k , webm_dash container, vp9@2039k, 60fps, video only, 76.27MiB
298          mp4        1280x720   720p60 2576k , mp4_dash container, avc1.4d4020@2576k, 60fps, video only, 96.37MiB
334          webm       1280x720   720p60 HDR 4338k , webm_dash container, vp9.2@4338k, 60fps, video only, 162.28MiB
303          webm       1920x1080  1080p60 3585k , webm_dash container, vp9@3585k, 60fps, video only, 134.10MiB
299          mp4        1920x1080  1080p60 4544k , mp4_dash container, avc1.64002a@4544k, 60fps, video only, 169.99MiB
335          webm       1920x1080  1080p60 HDR 6738k , webm_dash container, vp9.2@6738k, 60fps, video only, 252.07MiB
308          webm       2560x1440  1440p60 10376k , webm_dash container, vp9@10376k, 60fps, video only, 388.12MiB
336          webm       2560x1440  1440p60 HDR 16232k , webm_dash container, vp9.2@16232k, 60fps, video only, 607.18MiB
315          webm       3840x2160  2160p60 25568k , webm_dash container, vp9@25568k, 60fps, video only, 956.39MiB
337          webm       3840x2160  2160p60 HDR 28865k , webm_dash container, vp9.2@28865k, 60fps, video only, 1.05GiB
18           mp4        640x360    360p  655k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 24.53MiB
22           mp4        1280x720   720p 1778k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
` 
but why didnt it encode 4k then?

**Comment by DanielnetoDotCom** [comment]
from what command line did you get this result?

**Comment by DanielnetoDotCom** [comment]
OK, for now, we must force the MP4 to avoid errors, and the 4k is on webm

maybe we will update it in the future to allow use webm download as well

**Comment by Sandra-UwU-neko** [comment]
alright then thats all c: i which you a nice morning / day / evening / night
