### ISSUE TITLE
Website shows "Under Maintanance" after update

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo-Encoder#357]
So I did the update to latest on our video portal and now it is stuck in "Under Maintanance".  I have looked at the configurations, etc. and non of that has changed.  Need to get portal back online.  Any help would be appreciated.    https://video.ivrata.com
is the troubled portal.

**Comment by DanielnetoDotCom** [comment]
Check your log files (streamer and apache)

**Comment by tbryantAE** [comment]
System update from older build was corrupted.  I redid the sqldb updates and it is working now.
