### ISSUE TITLE
Change localhost to domain name

### ISSUE THREAD

**Issue by rahulmasal** [WWBN/AVideo-Encoder#359]
Dear Support Team,

Please provide solution for this problem.

Exact issue: at start we configured Encoder as localhost now we buy domain and need to change localhost to domain name.

we have own server so please guide us because  when we access /upload url many scripts not working properly.

![image](https://user-images.githubusercontent.com/22212803/111899412-9663b400-8a52-11eb-8c0b-3da26c3a7df9.png)

**Comment by akhilleusuggo** [comment]
You need to go to videos/ directory ( on the encoder ) . Change the your localhost url to new_domain_name .
Maybe you will need to change something on the database if you changed the default setting ( url streamer etc ).

Easiest way is to re-install the entire encoder , to avoid unnecessary errors debugging .( it takes 2mn , you have nothing valuable there to lose ).

**Comment by rahulmasal** [comment]
how to remove previous and install new one please guide

**Comment by akhilleusuggo** [comment]
remove the entire directory , and installed back as you did the first time .

You may wanna delete the database too . But you can also ignore the previous one , just give a different name ( to the database ) to your new installation .
