### ISSUE TITLE
Cosmetic defect in Encoder affecting usage

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo-Encoder#364]
The top bar constantly covers the encoder tabs and is difficult to use. Look at the picture

![Captura de pantalla de 2021-03-30 09-58-53](https://user-images.githubusercontent.com/5683921/112958305-a1010600-9142-11eb-9995-a609ea4bed92.png)

It could be solved by adding something like this in the css:

`.col-md-8 {
    margin-top: 50px;
}
#rightContainer {
    margin-top: 50px;
}`

**Comment by DanielnetoDotCom** [comment]
Looks for me you have a problem with your encoder "first streamer record"

it is not loading the streamer css

anyway, I will send an update to prevent this problem
