### ISSUE TITLE
HLS ffmpeg command mixed (hardcoded and db)

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo-Encoder#369]
Hi together,

i was playing around with the dynamic HLS encoding settings and it looks like the string i can change in the gui isnt used everywhere.
So my changes (hls_time 6->30) are reflected in some resulting m3u8 files but not in others:

![hls_time_bug1](https://user-images.githubusercontent.com/50199132/114366779-0bbb3400-9b7c-11eb-86c7-eda5d4052589.png)

As you can see the executed command mixes the settings out of the gui with some hardcoded:

![hls_time_bug3](https://user-images.githubusercontent.com/50199132/114366966-41601d00-9b7c-11eb-91c3-214cfa1a4e8d.png)

These i have found here:

![hls_time_bug4](https://user-images.githubusercontent.com/50199132/114367030-52a92980-9b7c-11eb-91ac-2dbffedba8a5.png)

For sure it shouldnt be like that and the gui-settings should be used everywhere!

**Comment by DanielnetoDotCom** [comment]
Check this 
![Uploading image.png…]()

**Comment by DanielnetoDotCom** [comment]
Check this 

![image](https://user-images.githubusercontent.com/18009293/114401086-f55fa900-9b78-11eb-8f54-770cb3b2e4e0.png)

**Comment by morbificagent** [comment]
Yes i have changed this but as result this settings are only reflected for the res720/index.m3u8
The others like res1080/index.m3u8 dont use these settings as they are generated by the hardcoded command in Format.php

**Comment by DanielnetoDotCom** [comment]
Not suppose to if you are using the automatic resolution option

**Comment by morbificagent** [comment]
The automatic resolution option is reading the master index.m3u8 and automatically jumps to the ./resXXX/index.m3u8 with the best bandwidth-value possible.

But this has nothing to do with the fact that the string for the "Dynamic HLS" in the gui isnt used for all ./resXXX/index.m3u8-files as it should be.

Yes for sure its playing if i use the auto-resolution option but thats not the case.

I think you only have to change the code in Format.php which is hardcoded to "get it from the db like the gui" and so we have ONE place for the settings and not like now two (gui->db and hardcoded->Format.php)

**Comment by DanielnetoDotCom** [comment]
Hi, you were right

this should fix
