### ISSUE TITLE
AVideo Encoder install stalled processed status [possible code error]

### ISSUE THREAD

**Issue by RememberForgottenHits** [WWBN/AVideo-Encoder#377]
Hi,

**Im use ubuntu 20.04 & Apache on VPS server. Didn't find an answer to your problem here.

Avideo streaming was successfully installed on the web domain https://mustream.info The problem is now installing AVideo Encoder on the subdomain https://upload.mustream.info The domain is working and the installation website is open.

ERROR LOG in /var/log/apache2/upload.mustream.info.error.log**

 ```
[Wed Apr 28 21:48:00.815849 2021] [proxy_fcgi:error] [pid 2449027] [client 85.76.167.230:52136] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/mustream.info/public_html/upload/objects/../videos/configuration.php): failed to open stream: No such file or directory in /var/www/mustream.info/public_html/upload/objects/Login.php on line 4PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/mustream.info/public_html/upload/objects/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/mustream.info/public_html/upload/objects/Login.php on line 4', referer: https://upload.mustream.info/install/index.php
[Wed Apr 28 21:53:15.504947 2021] [proxy_fcgi:error] [pid 2449382] [client 85.76.167.230:40598] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '=' in /var/www/mustream.info/public_html/upload/objects/Login.php on line 4', referer: https://upload.mustream.info/install/index.php 

```
**Content in /var/www/mustream.info/public_html/upload/objects/Login.php first 8 rows**

```
<?php
header('Set-Cookie: cross-site-cookie=name; SameSite=None; Secure');
if (!class_exists('Login')) {
    require_once dirname(__FILE__) . '/../videos/configuration.php';
    require_once dirname(__FILE__) . '/Streamer.php';

    class Login { 

```

**if i'm add line include_path='.:/usr/share/php' in row 4 the installation process stops in the same way!!**

```
<?php
header('Set-Cookie: cross-site-cookie=name; SameSite=None; Secure');
if (!class_exists('Login')) {
	include_path='.:/usr/share/php'
    require_once dirname(__FILE__) . '/../videos/configuration.php';
    require_once dirname(__FILE__) . '/Streamer.php';

    class Login { 
```

**APACHE error log there are no notes.

I discovered another such problem, that this directory path is incorrect /var/www/mustream.info/public_html/upload/objects/../videos/configuration.php) 
No "videos" directory
THAT would be the right directory path /var/www/mustream.info/public_html/upload/objects/configuration.php)

I think there is an error somewhere in the code

`[Thu Apr 29 10:13:33.998114 2021] [proxy_fcgi:error] [pid 2455522] [client 85.76.167.230:55780] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/mustream.info/public_html/upload/objects/configuration.php): failed to open stream: No such file or directory in /var/www/mustream.info/public_html/upload/objects/Login.php on line 4PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/mustream.info/public_html/upload/objects/configuration.php' (include_path='.:/usr/share/php') in /var/www/mustream.info/public_html/upload/objects/Login.php on line 4', referer: https://upload.mustream.info/install/index.php
`
then i added the file --> /var/www/mustream.info/public_html/upload/objects/configuration.php  its missing entry (include_path='.:/usr/share/php') line number 4

AFTER

```
<?php

if (!class_exists('Configuration')) {
	
    if (!class_exists('ObjectYPT')) {
        require_once 'Object.php';
    }
```

BEFORE

```
<?php

if (!class_exists('Configuration')) {
	(include_path='.:/usr/share/php')
    if (!class_exists('ObjectYPT')) {
        require_once 'Object.php';
    }
```

But the error is still the same, isn't that the problem (include_path='.:/usr/share/php')   How to fix it?

![encoder-install-processing](https://user-images.githubusercontent.com/34457020/116460259-8750fc80-a86f-11eb-9913-0cb2d2689c70.png)

`     `

**Comment by DanielnetoDotCom** [comment]
seems to me you do not have the mod-rewrite properly configured.

did you use the `git clone` to get the files?

we do not support control panel installations we recommend a clean Ubuntu

**Comment by RememberForgottenHits** [comment]
Thank you for the answer!

I am using a Contabo VPS XL SSD (10 vCPU Cores, 60 GB RAM, 1.6 TB SSD, 1 Gbit/s Port) server where it is installed cleanly only ubuntu 20.04. 
This server is currently running; Apache, PHP, Mysql + itself later installed WEBMIN
Currently working there: 2x wordpress webpage+2x different domain name
In addition to these services, I install an Avideo streaming website + AVideo-Encoder

I used GIT to clone the folder content for AVideo  & AVideo-Encoder

Which file do I need to examine or show you for help?

**Comment by DanielnetoDotCom** [comment]
Check the apache log, and also the XHR log 

![image](https://user-images.githubusercontent.com/18009293/116587145-91670f80-a8f0-11eb-836c-6843d230847e.png)

**Comment by RememberForgottenHits** [comment]
Thanks for your help and tips! :) 

I did a new clean installation! Because my streamer website empty anyway :) There seemed to be problems with different conf. 

There seemed to be problems with different conf filesfiles!!!
