### ISSUE TITLE
site is banned

### ISSUE THREAD

**Issue by HESSEBO** [WWBN/AVideo-Encoder#396]
After not using one of site streamers for quite sometimes, now my encoders giving me a message that states "site is banned". How can I fix this issue assuming that it may have been disabled or inactive some how. 
Thanks 

![Screenshot 2021-06-22 010528](https://user-images.githubusercontent.com/43477304/122833667-0c97e100-d2f6-11eb-9fd2-a4b111dee29c.png)

**Comment by DanielnetoDotCom** [comment]
This is due porn content 
Porn content is forbidden

**Comment by VWarte** [comment]
Avoid AVideo for that purpose. There is a backdoor in this script that exposes the content you are hosting, even if your site is not public accessible.
