### ISSUE TITLE
Privacy issues With AVideo Encoder/WWBN

### ISSUE THREAD

**Issue by va3jfl** [WWBN/AVideo-Encoder#400]
Many have asked this question regarding a block and a possible back door to private Avideo-Encoder instances But instead you simply ban and lock the topics, I spend big money with your premium plugins.  Over 100 dollars and deserve to know what is going on. Silly I'm not asking for your help to run a "porn" site im asking a legit question.

Can you confirm, that either AVideo or AVideo-Encoder has a build in BACKDOOR/FUNCTION, that exposes private content to unauthorized parties/groups.

That's all we want to know. Not a Christian sermon. Thanks

And oh here is a link to the invoice I paid. Not very Christian of you to just take money for premium plugins and just run and ban people. 

https://drive.google.com/file/d/1BaZTiTa8QOysHhIIM6-O5pTCTZfIuN_3/view?usp=sharing

**Comment by DanielnetoDotCom** [comment]
I can guarantee, there is no backdoor, but I will not help to unban banned sites
