### ISSUE TITLE
webm can't play on iPhone/iPad

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo-Encoder#403]
i was encoded .MP4 to WEBM.
On PC fine but can't play on the iPhone/iPad, i was tried on safari/chrome, both of them can't play.
how to fix ?

**Comment by DanielnetoDotCom** [comment]
maybe webm is not compatible with Apple.

you should use MP4 or HLS

**Comment by pedro0606** [comment]
can convert to mp4 and webm in the same time ?
can the player will automatically choose mp4/webm ?

**Comment by DanielnetoDotCom** [comment]
Sorry currently we do not have that, but we may add this in the future
