### ISSUE TITLE
I was bought the video hls plugin but can't encode to hls

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo-Encoder#404]
![image](https://user-images.githubusercontent.com/57143299/127005823-de98d3ae-7c67-4713-8ff8-c56e29683d19.png)
What is problem ? where i can check logs ?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you are missing the php-zip

try this 

`apt install php-zip`

If still failing check your encoder logs

**Comment by pedro0606** [comment]
tks so much, now it work fine.
How to protect .m3u8 ?
i was saw a tocken on the m3u8 link but still can play it on other 
![image](https://user-images.githubusercontent.com/57143299/127021595-76884fe8-2321-43d1-8ac5-3ea171b131da.png)
what is mistake with hls encrypted ?

**Comment by DanielnetoDotCom** [comment]
the token has an expiration time, test it in another browser (NOT in a tab)

**Comment by pedro0606** [comment]
on other browser still play normal and on the other pc on other network , too.
maybe hls aes didnt work

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean

the tokens protect against unauthorized file download.

if you want to not show the video for some users you may need a subscription or a payperview

**Comment by DanielnetoDotCom** [comment]
I reboot seems to bring back your site, 

for some reason your MySQL was dead

**Comment by pedro0606** [comment]
> I reboot seems to bring back your site,
> 
> for some reason your MySQL was dead

you can reboot my site via your source code ?

**Comment by pedro0606** [comment]
> I am not sure what you mean
> 
> the tokens protect against unauthorized file download.
> 
> if you want to not show the video for some users you may need a subscription or a payperview

that mean, i copy the .m3u8 url and can play on other website, browser with nativehls plugin

**Comment by DanielnetoDotCom** [comment]
When you do a test like that make sure you are using and incognito browser and you are not logged as admin

admin will always get approved and also once you approve with the token the script will memorize it and will not require the token anymore

**Comment by pedro0606** [comment]
yes, i open index.m3u8 url on the new browser with nativehls plugin. play fine, hls encrypted not work
![image](https://user-images.githubusercontent.com/57143299/127025490-698b5fdd-3621-4ea4-8f93-ec9f58e44c47.png)
so, someone else can steal my hls link and embed it on their website

**Comment by DanielnetoDotCom** [comment]
can you share here an HLS link from your site?

**Comment by pedro0606** [comment]
> can you share here an HLS link from your site?

Plz try this url
http://aimovies.one/videos/video_210727052703_fa40/index.m3u8

**Comment by DanielnetoDotCom** [comment]
Hi, I could confirm it was ignoring the Chrome browser, can you please update your VideoHLS plugin to version 5.4 

I am pretty sure this problem is resolved

**Comment by pedro0606** [comment]
Now ok, thank so much.
