### ISSUE TITLE
Unable to download encoder using git

### ISSUE THREAD

**Issue by outreach** [WWBN/AVideo-Encoder#405]
I tried to download the encoder using the following commands but they do not now work:
**$ sudo git https://github.com/WWBN/AVideo-Encoder.git**
git: 'https://github.com/WWBN/AVideo-Encoder.git' is not a git command. See 'git --help'.

**$ sudo git https://github.com/WWBN/AVideo-Encoder**
git: 'https://github.com/WWBN/AVideo-Encoder' is not a git command. See 'git --help'.

Please advise. Any help would be most appreciated.

Thanks so much.

**Comment by DanielnetoDotCom** [comment]
Should be` git clone https://github.com/WWBN/AVideo-Encoder.git`

I recommend you to use google to learn how to use Git

**Comment by outreach** [comment]
Duh on my part! Yes, I left out the clone part. Thanks.
