### ISSUE TITLE
Allow multiple encoding at the same time

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo-Encoder#407]
Is there a way to allow multiple encoding running at the same time? The use case is when the encoder server has multiple GPUs or high thread count CPUs, I can speed up the encoding process greatly if I can run multiple encodings at the same time.

**Comment by DanielnetoDotCom** [comment]
You may want to use this ...

https://github.com/WWBN/AVideo-Encoder-Network

or you may want to add the variable `$global['concurrent']` in your Encoder/videos/configuration.php

For example:

`$global['concurrent'] = 3;`

you will encode up to 3 videos at the same time

**Comment by aolvictim** [comment]
Got it. Thanks

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom wow, didn't know that. You need to update the wiki, specially with this hidden variable as we did on AVideo main site.

https://github.com/WWBN/AVideo/wiki/Configuration.php-variable-(-some-are-hidden-)

**Comment by DanielnetoDotCom** [comment]
This  variable is for the encoder I will create something similar on the encoder project

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo-Encoder/wiki/Configuration.php-variable-(-some-are-hidden-)

**Comment by akhilleusuggo** [comment]
Thank you !
