### ISSUE TITLE
Use yt-dlp instead of youtube-dl

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo-Encoder#420]
From my experience, `youtube-dl` has a lot of issues and is not actively maintained. I have switched to `yt-dlp` instead and is much faster and stable. Have you considered using `yt-dlp` as default instead? It's a drop in replacement.

**Comment by jengajenga** [comment]
do you have the install script?

**Comment by DanielnetoDotCom** [comment]
Is yt-dlp the same command lines as youtube-dl?

I am away from pc now but what is the link for the project?

**Comment by jengajenga** [comment]
> Is yt-dlp the same command lines as youtube-dl?
> 
> I am away from pc now but what is the link for the project?

try this

https://github.com/yt-dlp/yt-dlp

**Comment by aolvictim** [comment]
Yes that's the correct project. From my experience the usage is identical to `youtube-dl`.

**Comment by DanielnetoDotCom** [comment]
If it is identical you can install it and add this to your configuration.php file

`$global['youtube-dl'] = 'yt-dlp';`

or maybe is this 

`$global['youtube-dl'] = '/usr/local/bin/yt-dlp';`

please try and let me know

**Comment by aolvictim** [comment]
Yes that's what I've done and it works. My question was more of should we just switch the default to use `yt-dlp` instead since it's more reliable and actively maintained.

**Comment by jengajenga** [comment]
> If it is identical you can install it and add this to your configuration.php file
> 
> `$global['youtube-dl'] = 'yt-dlp';`
> 
> or maybe is this
> 
> `$global['youtube-dl'] = '/usr/local/bin/yt-dlp';`
> 
> please try and let me know

let me try this...

**Comment by DanielnetoDotCom** [comment]
If yt-dlp is working better, keep it. you can revert it to youtube-dl at any momment.

**Comment by aolvictim** [comment]
Sounds good. Thanks
