### ISSUE TITLE
Unable to encode videos: ffmpeg returns "Option allowed_extensions not found"

### ISSUE THREAD

**Issue by sizious** [WWBN/AVideo-Encoder#423]
Ola,

We have an issue with the AVideo Encoder. After encoding the video, the process is locked and the `null` message is shown in the Queue Log.

After investigating, I found the error.

```
[03-Dec-2021 08:30:18 UTC] videoFileHasErrors: errors found on video file /var/www/avideo/upload/videos/avideoTmpFile_136_streamers_id_1__720.mp4 
Option allowed_extensions not found.
```
As you might see, the function `videoFileHasErrors` is displaying the following message: `Option allowed_extensions not found.`. This message is generated by FFmpeg.

After browsing the code, the issue is [here](https://github.com/WWBN/AVideo-Encoder/blob/bad560455c8c3cb70691c709d63b81901c3975da/objects/Format.php#L761). As you might see, the `-allowed_extensions ALL` is not allowed here.

May you please fix that?

Thank you very much!

**Comment by sizious** [comment]
FYI, after removing this option from the command line, the issue is solved.

**Comment by DanielnetoDotCom** [comment]
what FFMPEG version are you running?

this option is required to be able to use it for HLS format

**Comment by sizious** [comment]
Hi Daniel,

Thanks for your answer, here is the output of my FFmpeg:

```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Comment by DanielnetoDotCom** [comment]
I also use FFMPEG version 4 and I do not have this issue

can you please share the encoder log when this error happens so I can understand where exactly it crashes?

**Comment by DanielnetoDotCom** [comment]
Now if the code fails with the allowed_extensions it will try again without it.
so it should work in any case.

**Comment by sizious** [comment]
Ola Daniel,

First of all, thank you for the fix! 👍🏻

To answer to your questions,

I think you are using a more recent/different build. Mine is FFmpeg coming from Ubuntu repositories, I guess it's more older because basically, it doesn't support the `-allowed_extensions` command line extension switch. So basically, there is no crash, just that message `Option allowed_extensions not found.` when `videoFileHasErrors` was called.

I'm curious, which version of FFmpeg are you using exactly? What's output of `ffmpeg -version` on your system?
