### ISSUE TITLE
ffmpeg -v error

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Encoder#433]
Hello back;

I've spend sometime playing with docker,compose and swarm. I wanted to implement the same for AVideo.
I've been away for long, many things changed ofc. 

Now I see something weird after encoding finishes.

`ffmpeg -v error -i /var`

Do you mind explain what does it do?

![image](https://user-images.githubusercontent.com/52116577/162055410-58a6a46e-6f8f-4d10-83c7-04cecf875c50.png)

![image](https://user-images.githubusercontent.com/52116577/162056480-6dffcb14-b979-46d7-a36e-17813b692e0d.png)

**Comment by DanielnetoDotCom** [comment]
Before transferring the file to the streamers we check for errors

in case there was an error on the transcoding we do not send it

**Comment by akhilleusuggo** [comment]
But it's taking longer then anticipated.

`ffmpeg -v error -i /var/www/html/AVideo-Encoder/videos/avideoTmpFile_4_streamers_id_1__HD.mp4 -f null -`

Almost a re-encoding. Is there any param to disable the check?

**Comment by DanielnetoDotCom** [comment]
No there is no parameter and the error check suppose to be very fast as long as it does not transcode anything.

**Comment by akhilleusuggo** [comment]
Yes, but the problem with this feature is that not all errors are recoverables, and not all errors are bad.

Example I'm getting :

`Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2447 >= 2447`

And the video keeps looping trying to fix it.

This is a bug error, not a real error, since the video is playable on browser, and the error doesn't have real value.
I hope in the future a feature to bypass this check, most of my videos ( home project / movies etc ) I use `-c copy`

**Comment by DanielnetoDotCom** [comment]
Make a git pull and add `$global['byPassVideoFileHasErrors'] = 1;` in your configuration.php file

**Comment by akhilleusuggo** [comment]
Works! Thank you.
