### ISSUE TITLE
How to setup Streamer and Encoder on two separate servers?

### ISSUE THREAD

**Issue by guillaumesoucy94** [WWBN/AVideo-Encoder#445]
Hello, 

I need to setup the streamer and the encoder on two different servers. When doing so, I'm not able to login into the streamer from the encoder. 

The /etc/hosts files on both, streamer and encoders are written in a way to make the streamer domain resolving to the server local IP and same thing for the encoder. 

This is both /etc/hosts files:

Encoder server:

192.168.2.135 zawacktv.com
192.168.2.135 gaming.zawacktv.com
192.168.2.119 mail.zawack.net

Streamer server:

192.168.2.197 encoder.zawacktv.com
192.168.2.197 encoder.gaming.zawacktv.com
192.168.2.119 mail.zawack.net

Remotely

The same issues is happening. A Records are in place so encoder.zawacktv.com and zawacktv.com are resolving, I can see the encoder site, I can login to the streamer site but, the encoder isn't able to login into the streamer site when working locally or remotely. 

When entering credential, the page is reloading without showing the encoder interface.

![Screenshot at 2022-07-08 03-43-14](https://user-images.githubusercontent.com/22561876/177943654-21f1e855-ce24-450c-86cb-c75fc9eb4805.png)
								
I will need some help please. 

Best regards, 

Guillaume

**Comment by DanielnetoDotCom** [comment]
Check the encoder and streamer log file . But looks like the encoder cannot see the streamer

**Comment by guillaumesoucy94** [comment]
Hello Daniel, 

This is the encoder logs:
https://plik.zsites.ca/file/3y1SjLk182HEvdya/yHhFLKA8PxxuYP1M/avideo-encoder.log

And the streamer logs:
https://plik.zsites.ca/file/3y1SjLk182HEvdya/WVoo2zURRW4IYL91/avideo-streamer.log

The streamer logs is a bit long but, if you jump to the end it says things about login. The encoder ones are shorter as I just deploy the VM.

Best regards, 

Guillaume

**Comment by DanielnetoDotCom** [comment]
on your encoder log, there is no login attempt

maybe it is a JS error on the encoder side.

check the JS error console.

check your Encoder/videos/configuration.php -> `$global['webSiteRootURL'] = "...???";`

make sure $global['webSiteRootURL'] is your public URL

**Comment by guillaumesoucy94** [comment]
Good evening,

for `$global['webSiteRootURL'] = "...???";` line, I do have: `$global['webSiteRootURL'] = 'https://encoder.zawacktv.com/';`

encoder.zawacktv.com is reachable from the entire internet it is also resolving from the streamer server which is another server on the same network. I had to add `192.168.2.197 encoder.zawacktv.com` in  /etc/hosts on the streamer for that. 

`192.168.2.135 zawacktv.com` has been also added in /etc/hosts on the encoder server.

In despite of everything, it is not working properly for now. Everything was working before, when the streamer and the encoder was on the same server. 

Best regards, 

Guillaume

**Comment by guillaumesoucy94** [comment]
Hello, 

I still need some help. 

Thank-you in advance!

Guillaume

**Comment by DanielnetoDotCom** [comment]
Provide the js console screenshot

**Comment by guillaumesoucy94** [comment]
Hello, 

Can you please help me finding the java script console? I really don't know where to go to get that. 

Thank-you very much.

Guillaume

**Comment by guillaumesoucy94** [comment]
Hello, 

The update did the trick but, it now take a while to login. I do have other instances and the logins are instant. 

Thanks, 

Guillaume

**Comment by DanielnetoDotCom** [comment]
This Update requires you to update all our products: Streamer, Paid plugins, Encoder, and Encoder-Network (git pull)

**Comment by guillaumesoucy94** [comment]
oh ok, I see. Will do this. Thank-you Daniel!

**Comment by guillaumesoucy94** [comment]
Hello, 

I did a `git pull ` at both, streamer server and encoder server, the accounts still taking a while to logins. When finally logged, everything are very quick to load. What to do next?

Regards,

Guillaume

**Comment by DanielnetoDotCom** [comment]
if there is no problem anymore, do not do anything. if still a problem check the logs

**Comment by guillaumesoucy94** [comment]
Yes there still and issue, it takes a lot of time to login. Into the streamer and the encoder as well. Which logs do I need to check?

Thank-you, 

Guillaume

**Comment by DanielnetoDotCom** [comment]
Share the streamer  avideo.log

**Comment by guillaumesoucy94** [comment]
Hi Daniel, 

Updating Avideo and the Encoder just fixes the issues. It is now fast as before.

Thank-you,

Guillaume
