### ISSUE TITLE
Encoder install

### ISSUE THREAD

**Issue by Tinoisthe** [WWBN/AVideo-Encoder#447]
I'm following the install guide and these are the only 3 i can't get to turn green
Since AVideo 2.1 we use exiftool to determine if an video is landscape or portrait
libimage-exiftool-perl is already the newest version (11.88-1ubuntu0.1

FFmpeg is not enabled, make sure your FFMPEG is 3.x or greater
ffmpeg is already the newest version (7:4.2.7-0ubuntu0.1).

 youtube-dl is not enabled
Requirement already satisfied: youtube-dl in /usr/local/lib/python3.8/dist-packages (2021.12.17)

![1657274750316](https://user-images.githubusercontent.com/76804686/178092183-4ba711ff-f2d8-4b26-8277-fc3e1391ffef.png)

**Comment by DanielnetoDotCom** [comment]
Search for the error at the top "shell_sexec has been disabled"

seems to me you are using some type of control panel, what is not recommended

follow this tutorial https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x---For-AVideo-Encoder

**Comment by Tinoisthe** [comment]
still can't do it says MySQL error can't restart 
rest are the same 
will get new vps 
as the one I'm using now is out of storage and need more ram

and i will make sure it a fresh Ubuntu 20.

**Comment by DanielnetoDotCom** [comment]
that explains, to work properly you must have at least 50 GB of free space

I recommend starting with at least 150 GB storage

read this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements#disk-storage

**Comment by Tinoisthe** [comment]
ok thank you
