### ISSUE TITLE
External hardware encoders

### ISSUE THREAD

**Issue by pmanhutch** [WWBN/AVideo-Encoder#454]
better professional encoder….can I install a external high end hardware encoder to work with youphptube software and if so? Can you send me the documentation. Sometimes the Network encoder works. Thanks!

**Comment by DanielnetoDotCom** [comment]
> can I install a external high end hardware encoder to work with youphptube software and if so?

Yes

 > Can you send me the documentation. 

https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x---For-AVideo-Encoder

> Sometimes the Network encoder works. Thanks!

https://github.com/WWBN/AVideo-Encoder-Network#how-to-install

**Comment by pmanhutch** [comment]
Thanks Daniel!  For that information encoder is working now.
