### ISSUE TITLE
SELECT f.*, e.* FROM encoder_queue e LEFT JOIN formats f ON f.id = formats_id WHERE (status = 'encoding' OR status = 'downloading' OR status = 'downloaded' OR status = 'queue' OR status = 'error') ORDER BY priority ASC, e.id ASC \nError : ()

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo-Encoder#458]
Tell me ... I click, download the video, but I get this error. What's wrong?
![image](https://user-images.githubusercontent.com/56869986/198568048-bf8a9b1d-db62-43e1-a6e8-53ff2fcdf0ae.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure if that is really the issue.

can you please check your Encoder/videos/avideo.log file?

also try to run this SQL command manually on a terminal and check the results

**Comment by DittmerOk** [comment]
> I am not sure if that is really the issue.
> 
> can you please check your Encoder/videos/avideo.log file?
> 
> also try to run this SQL command manually on a terminal and check the results

Please tell me please the full path of the file, where is it located?

**Comment by DittmerOk** [comment]
> Your MySQL credentials are wrong
> 
> check your videos/configuration.php
> 
> <img alt="image" width="690" src="https://user-images.githubusercontent.com/18009293/198571284-4781f65a-c0d0-4452-b9d7-b0cc0a6be0c7.png">

Yes thank you. Fixed everything, everything works
