### ISSUE TITLE
streamer site is now allowed 

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo-Encoder#463]
Installed encoder. Tested, everything was fine. Moved it to another network. Without the Internet... to the cisco network. This error appeared ... what could be the reason for this?
![f66163d3-2ec9-4a8c-bcf9-2fa729210fa9](https://user-images.githubusercontent.com/56869986/208888376-599be6dc-9cdf-4b30-8ec3-28ce50b5869a.jpg)

**Comment by DanielnetoDotCom** [comment]
`php /var/www/html/AVideo-Encoder/install/makeEncoderPublic.php `

of course, replace `/var/www/html/AVideo-Encoder/` with your encoder installation path

**Comment by DittmerOk** [comment]
I found the first file. But what to do with it?I did not quite understand what is needed and where to replace. Can be more?
![2](https://user-images.githubusercontent.com/56869986/208932058-708a1f2a-29e0-410f-9227-253d8c0b547b.jpg)
![f66163d3-2ec9-4a8c-bcf9-2fa729210fa9](https://user-images.githubusercontent.com/56869986/208932071-ae5be9ad-7120-4378-a61b-3528815b740f.jpg)

**Comment by DittmerOk** [comment]
and the instructions tell me that the install file needs to be deleted

**Comment by DanielnetoDotCom** [comment]
get the install folder again and do not delete it. 

delete the folder is not required, it is a suggestion

**Comment by DittmerOk** [comment]
OK. I haven't deleted anything yet.
![2](https://user-images.githubusercontent.com/56869986/208943369-64f78a2f-0cf2-4cf1-a6f0-94a60d3f7df2.jpg)
.. so far everything is the same as in the photo above. What should I do about it?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo-Encoder/issues/463#issuecomment-1361342945

**Comment by DittmerOk** [comment]
I have two folders in var/www/ avideo and html. I have AVideo-Encoder in the AVideo folder. Do I need to move it somewhere?
![3](https://user-images.githubusercontent.com/56869986/208948772-9b1ec8c8-4c84-4c9d-8d53-80c2e9287f3d.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry I do not know about your folders

**Comment by DittmerOk** [comment]
Then tell me how it should be) what will I have in the AVideo-Encoder folder? which is located along the path /var/www/html/AVideo-Encoder/

**Comment by DittmerOk** [comment]
I installed according to this guide. 7th and 8th step.
https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server

**Comment by DittmerOk** [comment]
and the most interesting thing is that on a different network, with the same folder structure. encoder available

**Comment by DittmerOk** [comment]
Thanks. Understood. The problem was to change the allowstreamersUrl in database.
