### ISSUE TITLE
expand file storage space

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo-Encoder#464]
I have a 100 GB server. I have seen that all my downloaded videos are saved in the encoder/videos/ folder. How can I expand this space to include a second hard drive and use it only to store the downloaded video?

**Comment by DanielnetoDotCom** [comment]
if you want you can add another drive and create symbolic links for the videos folder.

also, we have those options...

https://github.com/WWBN/AVideo/wiki/Storage-Options

But I recommend this 

https://github.com/WWBN/AVideo/wiki/CDN-Storage

**Comment by DittmerOk** [comment]
thanks. everything worked out
