### ISSUE TITLE
video not uploaded to the server after update

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo-Encoder#471]
video is convected, but not uploaded to the server. What's wrong?
![1](https://user-images.githubusercontent.com/56869986/218948162-18c10fb7-0f84-4f2e-8fe2-d3ad95aca5f9.jpg)

**Comment by DittmerOk** [comment]
Yes, of course I pressed. And in the console there is some strange error
![1](https://user-images.githubusercontent.com/56869986/219105946-6bee2301-8c39-4335-a37f-606b2258de83.jpg)

**Comment by DanielnetoDotCom** [comment]
seems to be a permission issue.

give 777 permission to the videos directory and all its subdirectories

**Comment by DittmerOk** [comment]
yes thanks it works
