### ISSUE TITLE
Your videos directory must be writable

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo-Encoder#472]
![1](https://user-images.githubusercontent.com/56869986/218971655-b7b27d5e-2efb-434a-b95e-165499392a02.jpg)
I have created a folder. Now I need to give her rights. I give permission, but the command is not executed. What's wrong?

**Comment by DanielnetoDotCom** [comment]
there was a piece of miss information there

the update may fix the information. but the correct command may be ...

`sudo chmod -R 777 /var/www/html/AVideo/videos`
