### ISSUE TITLE
streamers, configuration, update disappear 

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo-Encoder#473]
![1](https://user-images.githubusercontent.com/56869986/219659470-b1d599f0-7710-4273-a7f7-834e8c4ec1d5.jpg)
why did my streamers, configuration, update disappear after updating the update

**Comment by DanielnetoDotCom** [comment]
I am not sure but looks like you are not admin.

you can make any user admin in your encoder 

try this

`cd /var/www/html/AVideo/Encoder/install && php makeAdmin.php`

and then type your username

**Comment by DittmerOk** [comment]
yes thanks, that helped. I registered the command and everything appeared. Although strange.
