### ISSUE TITLE
Can't install Encoder

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo-Encoder#507]
I am trying to install a new encoder and I get errors regarding files which are not in my directory after I git cloned the encoder.

There was a bootstrap.js error about a wrong path pointing to ./view/js/  insted of /node_modules/dist/js/
This one i fixed manually. However there is a file named sweetalert.js and main.js which the server doesn't find. Please check the git package again to make sure all files that are required are there.

Here are screen shots:
![Screen Shot 5783-08-02 at 12 55 08](https://user-images.githubusercontent.com/58882903/233836172-be5d3db8-1145-4cee-8214-d4f47e38de90.jpg)
![Screen Shot 5783-08-02 at 14 05 20](https://user-images.githubusercontent.com/58882903/233836193-4958e49a-0e07-40d7-aca9-678cac414a68.jpg)

**Comment by guymass** [comment]
can't seem to install it I will see if I can copy from my other server which is a working older installation and see if that works.

**Comment by DanielnetoDotCom** [comment]
please check your apache log

**Comment by guymass** [comment]
it doesn't records anything. This server is behind a proxy but the installation works after I fixed all the errors and place all the missing files, but still after a successful installation I got the message indicating there is not permission on /var/www in the apache.conf file which there was. I already have one encoder running in this manner you can check
https://encoder3.alive528.com, but now I want to install another encoder and I get all sorts of errors which are strange.

**Comment by guymass** [comment]
OK after installation I needed to upgrade my encoder I git pulled and wanted to update, it seems the update went fine and I got OK but when I refresh I gives me this error and puts me back on previous version:
![Screen Shot 5783-08-04 at 19 28 19](https://user-images.githubusercontent.com/58882903/234343313-d47a39c2-9418-457c-9dfc-48b60eec80ae.jpg)

**Comment by guymass** [comment]
![Screen Shot 5783-08-04 at 19 41 03](https://user-images.githubusercontent.com/58882903/234345425-e713f87d-9069-48e0-be06-b88635d39b75.jpg)
![Screen Shot 5783-08-04 at 19 40 45](https://user-images.githubusercontent.com/58882903/234345443-b5c6739d-1584-4698-b35d-95f5cf957021.jpg)

I think the database.sql file on the repository is old or outdated. I cannot upgrade my new encoder for some reason.

**Comment by guymass** [comment]
I have all these updates, do I need to install them all?
![Screen Shot 5783-08-04 at 19 51 16](https://user-images.githubusercontent.com/58882903/234347794-dddda8dd-ff40-401c-9ea6-248745046cb9.jpg)

**Comment by guymass** [comment]
I run all installations and still it shows me I have 17 updates. How to fix this?
![Screen Shot 5783-08-04 at 19 40 45](https://user-images.githubusercontent.com/58882903/234353476-7eebcfad-5ce0-4912-97fa-30c4049a16db.jpg)

![Screen Shot 5783-08-04 at 20 17 51](https://user-images.githubusercontent.com/58882903/234353511-ac01cb02-32e0-4189-96f3-9796bdd9cd77.jpg)

**Comment by guymass** [comment]
Even after importing all databases with:

#!/bin/bash

for file in updateDb*.sql; do
  echo "Importing $file"
  mysql -uencoder -ppassword encoder4 < "$file"
done

Still it doesn't go away. This is by far the most strangest encoder install I had, usually it take me 10m to setup.

**Comment by DanielnetoDotCom** [comment]
because you have so many updates, I guess the best for you is to delete encoder/videos/configuration.php and database and make a clean encoder installation

**Comment by guymass** [comment]
I installed it already 3 times and every time I set a new database. So either the database installation is faulty or some other issue.

**Comment by guymass** [comment]
Are all those SQL update files required to be in the updates directory in the repository?
![Screen Shot 5783-08-11 at 1 54 00](https://user-images.githubusercontent.com/58882903/235547862-2a726f8b-ce7c-4109-9dfc-68b36485ef88.jpg)

After installing yet again, only after I move all SQL files out of the updates directory do the updates message stop.
I cannot install any update, I can only import them one by one, if its actually needed. 

I would prefer having a complete single SQL file to install and after installing database.sql none of the updated work unless I imports them manually. So I cannot update and the version of the encoder is not displayed anymore.

![Screen Shot 5783-08-11 at 2 18 51](https://user-images.githubusercontent.com/58882903/235547889-a93e6f80-e4d1-49f7-aa4b-f6376230eb88.jpg)

And Finally, because I cannot updated properly the admin of this section is closed for me:

![Screen Shot 5783-08-11 at 2 23 13](https://user-images.githubusercontent.com/58882903/235548239-e839d8c5-1291-4cc1-b3f8-d195398facca.jpg)

**Comment by guymass** [comment]
Also I cannot save any of the allowed streamer sites at all. is there any way to get a complete V4 SQL databases so I will just import it completley without any updates?

**Comment by DanielnetoDotCom** [comment]
check your error logs

**Comment by guymass** [comment]
I did, there is nothing indicating any error, not in apache, mysql or any other.  Its just something either about the database itself. Other wise why would it not install all the updates? something is missing either in the main database.sql or with the other files. For now the encoder is working so i dont mind as much. I will try maybe to import a database from another encoder and see hot it works.

**Comment by DanielnetoDotCom** [comment]
you can import the SQL files manually to create your database.

**Comment by guymass** [comment]
That is what I did but that also give errors depending on which file I am importing, and BTW do I need to import all of them in order by version number?

**Comment by DanielnetoDotCom** [comment]
no, the default [database.sql](https://github.com/WWBN/AVideo-Encoder/blob/master/install/database.sql) is the latest, and no update is required.

**Comment by guymass** [comment]
then why all those updates are inside the updates/ folder waiting to be installed? any it could be maybe a problem with the installation of the server itself, maybe some other bug. I will close this for now.

**Comment by DanielnetoDotCom** [comment]
updates are only you have an old encoder and you want to migrate to the new one after the git pull

if it is a brand new install you do not need them
