### ISSUE TITLE
Is there a install just for the encoder?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo-Encoder#511]
I want to install this on a dedicated but I do not see a one stack install listed

**Comment by DanielnetoDotCom** [comment]
Basically, everything you need for Streamer you need for the encoder, 

use this https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer

escape the nginx installation and you should be good

**Comment by JoshWho** [comment]
kk thank you
