### ISSUE TITLE
PHP Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo-Encoder#523]
I now have this nonstop message in avideo.log and my site got very slow and hangs all the time after latest pull. Not sure yet what to do with this message, but if someone already been there and knows how to solve it I would appreciate it. BTW since when do we compile PHP?

It is set to 1024, but you have descriptors numbered at least as high as 1024.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in /var/www/html/AVideo/vendor/react/event-loop/src/StreamSelectLoop.php on line 303

**Comment by guymass** [comment]
OK now I restarted all three services of Apache, MySQL and YTPSocet and got the site back up, however I see the following repeating messages filling up my log file.

Live::getStatsObject get_data(https://alive528.com:8443/stat, 4) 
function: _error_log_debug Line: {1627} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: get_data Line: {1573} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: getStatsObject Line: {2212} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: _getStats Line: {1908} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: getStats Line: {9141} File: {/var/www/html/AVideo/objects/functions.php}
function: getStatsNotifications Line: {387} File: {/var/www/html/AVideo/plugin/Live/view/menuRight.php}
function: include Line: {64} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: getHTMLMenuRight Line: {348} File: {/var/www/html/AVideo/plugin/AVideoPlugin.php}
function: getHTMLMenuRight Line: {136} File: {/var/www/html/AVideo/view/include/navbar.php}
function: include Line: {348} File: {/var/www/html/AVideo/view/modeYoutube.php}
*** SCRIPT_NAME: /view/modeYoutube.php
[20-Dec-2023 22:56:32 Asia/Jerusalem] AVideoLog::DEBUG: Page generated in 0.3487 seconds. User: Not Logged - No Cache (/video/22314) FROM: 66.249.66.7 Browser: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.71 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) SCRIPT_NAME: /view/modeYoutube.php
[20-Dec-2023 22:56:32 Asia/Jerusalem] AVideoLog::DEBUG: 
***
Live::getStatsObject get_data(https://alive528.com:8443/stat, 4) 
function: _error_log_debug Line: {1627} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: get_data Line: {1573} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: getStatsObject Line: {2212} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: _getStats Line: {1908} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: getStats Line: {9141} File: {/var/www/html/AVideo/objects/functions.php}
function: getStatsNotifications Line: {387} File: {/var/www/html/AVideo/plugin/Live/view/menuRight.php}
function: include Line: {64} File: {/var/www/html/AVideo/plugin/Live/Live.php}
function: getHTMLMenuRight Line: {348} File: {/var/www/html/AVideo/plugin/AVideoPlugin.php}
function: getHTMLMenuRight Line: {136} File: {/var/www/html/AVideo/view/include/navbar.php}
function: include Line: {348} File: {/var/www/html/AVideo/view/modeYoutube.php}
*** SCRIPT_NAME: /view/modeYoutube.php
[20-Dec-2023 22:56:32 Asia/Jerusalem] AVideoLog::DEBUG:

**Comment by guymass** [comment]
I keep seeing this error n avideo.log file, do you know what do I need to do?

 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in /var/www/html/AVideo/vendor/react/event-loop/src/StreamSelectLoop.php on line 303
[26-Dec-2023 19:38:41 Asia/Jerusalem] PHP Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1024.

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not have this error on my side. I also never seen this error before

**Comment by guymass** [comment]
OK, things seem to have gone after a server update and reboot, so it was probably some internal bug. Closing this issue.
