### ISSUE TITLE
Error upload_max_filesize in php.ini

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo-Encoder#534]
@DanielnetoDotCom Danny, I did my first test by sending a local file to encode to the personal AVideo Encoder.
It presented the following error, asking to correctly configure `php.ini`
I made these changes to the encoder server... within Apache's php and CLI's php. But the error is still persistent.
I set it to `upload_max_filesize=4000M` both.
During installation I made the correct settings and it was approved.

`Erro The uploaded file exceeds the upload_max_filesize directive in php.ini`

Can you tell me in Ubuntu which php.ini file I should actually change for Encoder to work with local files?

![image](https://github.com/WWBN/AVideo-Encoder/assets/37880073/0058be79-90ad-48a3-bb67-b439aefe25df)

**Comment by DanielnetoDotCom** [comment]
you need to change 

```
post_max_size = 8G
upload_max_filesize = 8G 
```

**Comment by gbrn** [comment]
> post_max_size = 8G
> upload_max_filesize = 8G 

Ok, I made the respective changes and it worked correctly.
I would like to note that the changed file was on the AVideo Encoder server, directory:
`/etc/php/8.3/apache2` file php.ini
