### ISSUE TITLE
Bots don't track encoder

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo-Encoder#539]
@DanielnetoDotCom Danny, I think it's interesting to ensure that bots don't track encoder services... it's better not to have them listed in any search, to avoid undue access attempts.

![image](https://github.com/user-attachments/assets/850bb6cc-6aa4-4054-b91c-da0276e9f39c)

**Comment by DanielnetoDotCom** [comment]
Agree, right now I added the robots.txt

**Comment by gbrn** [comment]
Thanks!
